import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { audit,db,id,now } from "@/lib/database";
import { sendPushToAllUsers } from "@/lib/push";
const optionalText=z.string().max(240).nullable().optional(),optionalUrl=z.url().nullable().optional().or(z.literal(""));
const schema=z.object({title:z.string().trim().min(2).max(140),description:z.string().max(5000).default(""),startsAt:z.iso.datetime(),endsAt:z.iso.datetime(),location:optionalText,navigationUrl:optionalUrl,shopUrl:optionalUrl,mediaId:z.string().uuid().nullable().optional(),status:z.enum(["draft","published","archived"]).default("published")}).refine(value=>new Date(value.endsAt)>new Date(value.startsAt),{path:["endsAt"],message:"Das Ende muss nach dem Beginn liegen."});
function validationMessage(error:z.ZodError){const issue=error.issues[0],field={title:"Titel",description:"Beschreibung",startsAt:"Beginn",endsAt:"Ende",location:"Ort",navigationUrl:"Navigationslink",shopUrl:"Buchungslink",mediaId:"Titelbild"}[String(issue?.path[0])]||"Eingabe";return `${field}: ${issue?.message||"Bitte Wert prüfen."}`}
export async function GET(){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});return Response.json({events:db.prepare("SELECT id,title,description,starts_at startsAt,ends_at endsAt,location,navigation_url navigationUrl,shop_url shopUrl,media_id mediaId,status FROM public_events ORDER BY starts_at").all()})}
export async function POST(request:Request){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:validationMessage(parsed.error),field:parsed.error.issues[0]?.path[0]||null},{status:400});const eventId=id(),timestamp=now(),x=parsed.data;if(x.mediaId&&!db.prepare("SELECT 1 FROM media_files WHERE id=? AND mime_type IN ('image/jpeg','image/png','image/webp')").get(x.mediaId))return Response.json({error:"Das Titelbild wurde nicht gefunden oder hat ein ungültiges Format.",field:"image"},{status:400});db.prepare("INSERT INTO public_events (id,title,description,starts_at,ends_at,location,navigation_url,shop_url,media_id,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").run(eventId,x.title,x.description,x.startsAt,x.endsAt,x.location||null,x.navigationUrl||null,x.shopUrl||null,x.mediaId||null,x.status,timestamp,timestamp);audit(admin.id,"event.create","event",eventId,{title:x.title});if(x.status==="published")await sendPushToAllUsers({title:"Neuer Termin",body:"In der App wurde eine neue Veranstaltung veröffentlicht.",url:"/"}).catch(()=>undefined);return Response.json({id:eventId},{status:201})}
