import {spawn} from "node:child_process";
import {Readable} from "node:stream";
import fs from "node:fs/promises";
import path from "node:path";
import {requireAdmin,requireFreshAdmin} from "@/lib/auth";
import {audit} from "@/lib/database";
export const dynamic="force-dynamic";export const runtime="nodejs";
const root="/var/backups/mein-kraftbaum",pattern=/^\d{8}-\d{6}-(daily|update|manual|pre-restore)$/;
export async function GET(_:Request,{params}:{params:Promise<{name:string}>}){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const {name}=await params;if(!pattern.test(name))return Response.json({error:"Ungültiger Backupname."},{status:400});try{const info=await fs.stat(path.join(root,name));if(!info.isDirectory())throw new Error()}catch{return Response.json({error:"Backup nicht gefunden."},{status:404})}const child=spawn("tar",["-C",root,"-czf","-",name],{stdio:["ignore","pipe","pipe"]});audit(admin.id,"backup.download","backup",name);return new Response(Readable.toWeb(child.stdout) as ReadableStream,{headers:{"content-type":"application/gzip","content-disposition":`attachment; filename="${name}.tar.gz"`,"cache-control":"private, no-store"}})}
export async function DELETE(_:Request,{params}:{params:Promise<{name:string}>}){const admin=await requireFreshAdmin();if(!admin)return Response.json({error:"Deine letzte Anmeldung liegt zu lange zurück. Melde dich kurz ab und wieder an; danach kannst du das Backup löschen."},{status:403});const {name}=await params;if(!pattern.test(name))return Response.json({error:"Ungültiger Backupname."},{status:400});const dataDir=process.env.DATA_DIR||path.join(process.cwd(),"data");try{const info=await fs.stat(path.join(root,name));if(!info.isDirectory())throw new Error()}catch{return Response.json({error:"Das Backup wurde nicht gefunden oder bereits gelöscht."},{status:404})}try{await fs.access("/etc/systemd/system/mein-kraftbaum-backup-delete.path");await fs.writeFile(path.join(dataDir,"backup-delete-request"),`${name}\n`,{flag:"wx",mode:0o600});audit(admin.id,"backup.delete_requested","backup",name);return Response.json({ok:true,message:"Das Backup wird sicher gelöscht. Die Liste aktualisiert sich automatisch."},{status:202})}catch(error){if((error as NodeJS.ErrnoException).code==="EEXIST")return Response.json({error:"Ein anderer Backup-Löschauftrag läuft bereits. Warte kurz und versuche es erneut."},{status:409});return Response.json({error:"Der sichere Löschdienst fehlt. Spiele zuerst das aktuelle Update vollständig ein."},{status:503})}}
