import { execFile } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs/promises";
import path from "node:path";
import { requireAdmin } from "@/lib/auth";
import { audit } from "@/lib/database";
import { CODE_REVISION } from "@/lib/version";
const exec=promisify(execFile),dataDir=process.env.DATA_DIR||path.join(process.cwd(),"data");
export const dynamic="force-dynamic";export const runtime="nodejs";
export async function GET(){const admin=await requireAdmin();if(!admin)return Response.json({error:"Die Updateverwaltung ist ausschließlich für angemeldete Admins mit eingerichteter Zwei-Faktor-Anmeldung verfügbar."},{status:403});let updateStatus:unknown=null;try{updateStatus=JSON.parse(await fs.readFile(path.join(dataDir,"update-status.json"),"utf8"))}catch{updateStatus=null}let available=false,remoteRevision:string|null=null,checkError:string|null=null;try{const {stdout}=await exec("git",["ls-remote","origin","refs/heads/main"],{cwd:process.cwd(),timeout:5000});const remote=stdout.trim().split(/\s/)[0],{stdout:local}=await exec("git",["rev-parse","HEAD"],{cwd:process.cwd(),timeout:2000});available=Boolean(remote&&remote!==local.trim());remoteRevision=remote?remote.slice(0,7):null}catch{checkError="Die Updatequelle konnte nicht erreicht werden. Die laufende Revision wird weiterhin angezeigt."}return Response.json({currentRevision:CODE_REVISION,available,remoteRevision,checkError,updateStatus},{headers:{"cache-control":"no-store"}})}
export async function POST(){const admin=await requireAdmin();if(!admin)return Response.json({error:"Die Updateverwaltung ist ausschließlich für angemeldete Admins mit eingerichteter Zwei-Faktor-Anmeldung verfügbar."},{status:403});try{await fs.access("/etc/systemd/system/mein-kraftbaum-update.path")}catch{return Response.json({error:"Der sichere Update-Trigger fehlt auf dem Server. Führe das Installationsskript einmal als root aus; danach funktionieren weitere Updates direkt hier im Footer."},{status:503})}try{await fs.writeFile(path.join(dataDir,"update-request"),`${new Date().toISOString()} ${admin.id}\n`,{flag:"wx"});audit(admin.id,"update.start","system","application");return Response.json({ok:true,message:"Update wurde an den Server übergeben. Installation, Tests und Neustart beginnen automatisch."},{status:202})}catch(error){if((error as NodeJS.ErrnoException).code==="EEXIST")return Response.json({ok:true,message:"Eine Update-Anforderung liegt bereits vor. Bitte warte, bis die Installation abgeschlossen ist."},{status:202});return Response.json({error:"Die Update-Anforderung konnte nicht gespeichert werden. Prüfe mit dem Server-Preflight die Rechte des Datenverzeichnisses."},{status:503})}}
