import fs from "node:fs/promises";
import path from "node:path";
import {requireAdmin} from "@/lib/auth";
import {audit} from "@/lib/database";
import {z} from "zod";
export const dynamic="force-dynamic";export const runtime="nodejs";
const root="/var/backups/mein-kraftbaum",dataDir=process.env.DATA_DIR||path.join(process.cwd(),"data"),namePattern=/^\d{8}-\d{6}-(daily|update|manual|pre-restore)$/;
const retentionDefaults={daily:14,update:10,manual:10,"pre-restore":3};
const retentionSchema=z.object({daily:z.number().int().min(1).max(365),update:z.number().int().min(1).max(365),manual:z.number().int().min(1).max(365),"pre-restore":z.number().int().min(1).max(365)});
async function jsonFile(name:string){try{return JSON.parse(await fs.readFile(path.join(dataDir,name),"utf8"))}catch{return null}}
async function retention(){const parsed=retentionSchema.safeParse({...retentionDefaults,...await jsonFile("backup-retention.json")});return parsed.success?parsed.data:retentionDefaults}
export async function GET(){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});let names:string[]=[];try{names=await fs.readdir(root)}catch{/* Ein frischer Server hat eventuell noch kein Backup-Verzeichnis. */}const backups=[];for(const name of names.filter(value=>namePattern.test(value)).sort().reverse()){try{const info=await fs.stat(path.join(root,name)),manifest=JSON.parse(await fs.readFile(path.join(root,name,"manifest.json"),"utf8").catch(()=>"null"));backups.push({name,createdAt:manifest?.createdAt||info.birthtime.toISOString(),kind:manifest?.kind||name.split("-").at(-1),revision:manifest?.revision?.slice(0,12)||null,restorable:Boolean(manifest?.format==="mein-kraftbaum-backup"&&manifest?.version===1)})}catch{/* Unvollständige Verzeichnisse werden nicht angeboten. */}}return Response.json({backups,retention:await retention(),backupStatus:await jsonFile("backup-status.json"),backupDeleteStatus:await jsonFile("backup-delete-status.json"),restoreStatus:await jsonFile("restore-status.json")},{headers:{"cache-control":"no-store"}})}
export async function POST(){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});try{await fs.access("/etc/systemd/system/mein-kraftbaum-backup-request.path");await fs.writeFile(path.join(dataDir,"backup-request"),`${new Date().toISOString()} ${admin.id}\n`,{flag:"wx",mode:0o600});audit(admin.id,"backup.create_requested","backup","manual");return Response.json({ok:true,message:"Backup wurde an den Server übergeben."},{status:202})}catch(error){if((error as NodeJS.ErrnoException).code==="EEXIST")return Response.json({ok:true,message:"Ein Backup-Auftrag läuft bereits."},{status:202});return Response.json({error:"Der sichere Backup-Dienst fehlt. Führe das Installationsskript einmal erneut aus."},{status:503})}}
export async function PUT(request:Request){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const parsed=retentionSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Für jeden Backup-Typ sind 1 bis 365 Sicherungen zulässig."},{status:400});await fs.mkdir(dataDir,{recursive:true});const target=path.join(dataDir,"backup-retention.json"),temporary=`${target}.tmp`;await fs.writeFile(temporary,`${JSON.stringify(parsed.data,null,2)}\n`,{mode:0o600});await fs.rename(temporary,target);audit(admin.id,"backup.retention_updated","backup","retention",parsed.data);return Response.json({ok:true,message:"Aufbewahrungsgrenzen gespeichert. Sie werden nach dem nächsten erfolgreichen Backup angewendet.",retention:parsed.data})}
