import fs from "node:fs/promises";
import path from "node:path";
import {requireAdmin} from "@/lib/auth";
import {audit} from "@/lib/database";
export const dynamic="force-dynamic";export const runtime="nodejs";
const root="/var/backups/mein-kraftbaum",dataDir=process.env.DATA_DIR||path.join(process.cwd(),"data"),namePattern=/^\d{8}-\d{6}-(daily|update|manual|pre-restore)$/;
async function jsonFile(name:string){try{return JSON.parse(await fs.readFile(path.join(dataDir,name),"utf8"))}catch{return null}}
export async function GET(){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});let names:string[]=[];try{names=await fs.readdir(root)}catch{return Response.json({backups:[],backupStatus:null,restoreStatus:null})}const backups=[];for(const name of names.filter(value=>namePattern.test(value)).sort().reverse()){try{const info=await fs.stat(path.join(root,name)),manifest=JSON.parse(await fs.readFile(path.join(root,name,"manifest.json"),"utf8").catch(()=>"null"));backups.push({name,createdAt:manifest?.createdAt||info.birthtime.toISOString(),kind:manifest?.kind||name.split("-").at(-1),revision:manifest?.revision?.slice(0,12)||null,restorable:Boolean(manifest?.format==="mein-kraftbaum-backup"&&manifest?.version===1)})}catch{/* Unvollständige Verzeichnisse werden nicht angeboten. */}}return Response.json({backups,backupStatus:await jsonFile("backup-status.json"),restoreStatus:await jsonFile("restore-status.json")},{headers:{"cache-control":"no-store"}})}
export async function POST(){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});try{await fs.access("/etc/systemd/system/mein-kraftbaum-backup-request.path");await fs.writeFile(path.join(dataDir,"backup-request"),`${new Date().toISOString()} ${admin.id}\n`,{flag:"wx",mode:0o600});audit(admin.id,"backup.create_requested","backup","manual");return Response.json({ok:true,message:"Backup wurde an den Server übergeben."},{status:202})}catch(error){if((error as NodeJS.ErrnoException).code==="EEXIST")return Response.json({ok:true,message:"Ein Backup-Auftrag läuft bereits."},{status:202});return Response.json({error:"Der sichere Backup-Dienst fehlt. Führe das Installationsskript einmal erneut aus."},{status:503})}}
