import { generateRegistrationOptions,verifyRegistrationResponse } from "@simplewebauthn/server";
import type { RegistrationResponseJSON } from "@simplewebauthn/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { audit,db,now } from "@/lib/database";
import { passkeyConfig,saveChallenge,takeChallenge } from "@/lib/passkeys";
import { hashRecoveryCodes,makeRecoveryCodes } from "@/lib/two-factor";

const schema=z.object({response:z.unknown()});
export async function GET(){const admin=await requireAdmin({allowTwoFactorSetup:true});if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});try{const config=passkeyConfig(),existing=db.prepare("SELECT id,transports FROM passkey_credentials WHERE user_id=?").all(admin.id) as {id:string;transports:string}[],options=await generateRegistrationOptions({rpName:config.rpName,rpID:config.rpID,userName:admin.email,userID:new TextEncoder().encode(admin.id),attestationType:"none",authenticatorSelection:{residentKey:"preferred",userVerification:"required"},excludeCredentials:existing.map(x=>({id:x.id,transports:JSON.parse(x.transports)}))});saveChallenge(admin.id,options.challenge,"registration");return Response.json(options)}catch(error){return Response.json({error:error instanceof Error?error.message:"Passkey konnte nicht vorbereitet werden."},{status:400})}}
export async function POST(request:Request){const admin=await requireAdmin({allowTwoFactorSetup:true});if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Ungültige Passkey-Antwort."},{status:400});const challenge=takeChallenge(admin.id,"registration");if(!challenge)return Response.json({error:"Die Passkey-Anfrage ist abgelaufen."},{status:400});try{const config=passkeyConfig(),verification=await verifyRegistrationResponse({response:parsed.data.response as RegistrationResponseJSON,expectedChallenge:challenge,expectedOrigin:config.origin,expectedRPID:config.rpID,requireUserVerification:true});if(!verification.verified)return Response.json({error:"Passkey konnte nicht bestätigt werden."},{status:400});const credential=verification.registrationInfo.credential,recovery=makeRecoveryCodes(),hashed=await hashRecoveryCodes(recovery),timestamp=now();db.transaction(()=>{db.prepare("INSERT INTO passkey_credentials (id,user_id,public_key,counter,transports,device_type,backed_up,created_at) VALUES (?,?,?,?,?,?,?,?)").run(credential.id,admin.id,Buffer.from(credential.publicKey).toString("base64url"),credential.counter,JSON.stringify(credential.transports||[]),verification.registrationInfo.credentialDeviceType,verification.registrationInfo.credentialBackedUp?1:0,timestamp);db.prepare("UPDATE users SET two_factor_method='passkey',two_factor_enabled_at=?,recovery_codes=?,updated_at=? WHERE id=?").run(timestamp,JSON.stringify(hashed),timestamp,admin.id)})();audit(admin.id,"2fa.enable_passkey","user",admin.id);return Response.json({recoveryCodes:recovery})}catch{return Response.json({error:"Die Passkey-Prüfung ist fehlgeschlagen."},{status:400})}}
