import {z} from "zod";
import {requireAdmin} from "@/lib/auth";
import {audit,db,id,now} from "@/lib/database";
import {pushSettings,sendPush} from "@/lib/push";

const schema=z.object({audience:z.enum(["all","course"]),courseId:z.string().uuid().nullable().optional(),title:z.string().trim().min(2).max(80),body:z.string().trim().min(2).max(240),url:z.string().trim().max(500).refine(value=>value.startsWith("/")&&!value.startsWith("//"),"Nur interne App-Pfade sind erlaubt.").optional().default("/")});
const list=()=>db.prepare(`SELECT p.id,p.audience,p.course_id courseId,c.title courseTitle,p.title,p.body,p.target_url url,p.recipient_count recipientCount,p.delivered_count deliveredCount,p.failed_count failedCount,p.created_at createdAt,u.first_name||' '||u.last_name createdBy FROM push_messages p LEFT JOIN courses c ON c.id=p.course_id LEFT JOIN users u ON u.id=p.created_by ORDER BY p.created_at DESC LIMIT 100`).all();

export async function GET(){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});return Response.json({messages:list()},{headers:{"cache-control":"private, no-store"}})}
export async function POST(request:Request){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});if(!pushSettings())return Response.json({error:"Web Push ist noch nicht eingerichtet. Richte zuerst die Push-Schlüssel ein."},{status:409});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Bitte prüfe Titel, Nachricht und Empfängergruppe.",field:parsed.error.issues[0]?.path[0]||null},{status:400});const input=parsed.data;if(input.audience==="course"&&!input.courseId)return Response.json({error:"Bitte wähle den Kurs aus, dessen Teilnehmerinnen die Nachricht erhalten sollen.",field:"courseId"},{status:400});if(input.courseId&&!db.prepare("SELECT 1 FROM courses WHERE id=?").get(input.courseId))return Response.json({error:"Der gewählte Kurs wurde nicht gefunden.",field:"courseId"},{status:404});const users=(input.audience==="all"?db.prepare(`SELECT DISTINCT u.id FROM users u JOIN push_subscriptions p ON p.user_id=u.id AND p.enabled=1 WHERE u.role='user' AND u.status='active'`):db.prepare(`SELECT DISTINCT u.id FROM users u JOIN enrollments e ON e.user_id=u.id JOIN push_subscriptions p ON p.user_id=u.id AND p.enabled=1 WHERE u.role='user' AND u.status='active' AND e.course_id=?`)).all(...(input.audience==="course"?[input.courseId]:[])) as {id:string}[];let delivered=0,failed=0;for(const user of users){const result=await sendPush(user.id,{title:input.title,body:input.body,url:input.url||"/"});delivered+=result.delivered;failed+=result.failed}const messageId=id(),timestamp=now();db.prepare("INSERT INTO push_messages (id,course_id,audience,title,body,target_url,recipient_count,delivered_count,failed_count,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").run(messageId,input.audience==="course"?input.courseId:null,input.audience,input.title,input.body,input.url||"/",users.length,delivered,failed,admin.id,timestamp);audit(admin.id,"push_message.send","push_message",messageId,{audience:input.audience,courseId:input.courseId||null,recipients:users.length,delivered,failed});return Response.json({message:`Push-Nachricht wurde an ${users.length} erreichbare Teilnehmerin${users.length===1?"":"nen"} versendet.`,messageEntry:(list() as {id:string}[]).find(entry=>entry.id===messageId),recipientCount:users.length,deliveredCount:delivered,failedCount:failed},{status:201})}
