"use client";
/* Form rows are synchronized when another course is selected or dates are imported. */
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import {FormEvent,useEffect,useState} from "react";
import {appTimeZone,zonedInputValue,zonedLocalToIso} from "@/lib/app-time";

type Course={id:string;title:string;sessionCount:number;durationMinutes:number};
type Session={id:string;sequence:number;startsAt:string;endsAt:string};
type Row={sequence:number;date:string;time:string};
const blank=(sequence:number):Row=>({sequence,date:"",time:""});
function localParts(value:string){const local=zonedInputValue(value),[date,time]=local.split("T");return {date,time}}
function parseBulk(value:string){return value.split(/[\n,;]+/).map(item=>item.trim()).filter(Boolean).map(item=>{const match=item.match(/^(\d{1,2})\.(\d{1,2})\.(\d{4})\s+(\d{1,2}):(\d{2})$/);if(match)return {date:`${match[3]}-${match[2].padStart(2,"0")}-${match[1].padStart(2,"0")}`,time:`${match[4].padStart(2,"0")}:${match[5]}`};const iso=item.match(/^(\d{4}-\d{2}-\d{2})[ T](\d{2}:\d{2})$/);return iso?{date:iso[1],time:iso[2]}:null}).filter((item):item is Omit<Row,"sequence">=>Boolean(item))}

export function AdminSessionPlanner({course,notify}:{course:Course;notify:(message:string)=>void}){
  const [sessions,setSessions]=useState<Session[]>([]),[rows,setRows]=useState<Row[]>([]),[bulk,setBulk]=useState(""),[busy,setBusy]=useState(false),[editing,setEditing]=useState<string|null>(null),[editRow,setEditRow]=useState({date:"",time:""});
  async function load(){const response=await fetch(`/api/admin/courses/${course.id}/sessions`),result=await response.json();if(!response.ok){notify(result.error);return}const items=result.sessions as Session[],used=new Set(items.map(item=>item.sequence)),missing=Array.from({length:course.sessionCount},(_,index)=>index+1).filter(sequence=>!used.has(sequence));setSessions(items);setRows(missing.map(blank))}
  useEffect(()=>{void load()},[course.id,course.sessionCount]);
  function update(index:number,key:"date"|"time",value:string){setRows(current=>current.map((row,i)=>i===index?{...row,[key]:value}:row))}
  function importDates(){const parsed=parseBulk(bulk);if(!parsed.length){notify("Keine gültigen Termine erkannt. Beispiel: 01.07.2027 18:30, 08.07.2027 18:30");return}setRows(current=>current.map((row,index)=>parsed[index]?{...row,...parsed[index]}:row));notify(`${Math.min(parsed.length,rows.length)} Termine wurden übernommen. Bitte vor dem Speichern prüfen.`)}
  async function save(event:FormEvent){event.preventDefault();if(rows.some(row=>!row.date||!row.time)){notify(`Bitte fülle Datum und Startzeit für alle ${rows.length} noch offenen Einheiten aus.`);return}setBusy(true);try{const response=await fetch(`/api/admin/courses/${course.id}/sessions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({startsAt:rows.map(row=>zonedLocalToIso(`${row.date}T${row.time}`))})}),result=await response.json();if(!response.ok){notify(result.error);return}notify(`${result.count} Termine wurden erfolgreich angelegt. Nummer, Titel und Endzeit hat die App automatisch ergänzt.`);await load()}catch(error){notify(error instanceof Error?error.message:"Die Termine konnten nicht gespeichert werden. Prüfe die Verbindung und versuche es erneut.")}finally{setBusy(false)}}
  function beginEdit(item:Session){setEditing(item.id);setEditRow(localParts(item.startsAt))}
  async function updateSession(item:Session){if(!editRow.date||!editRow.time){notify("Bitte gib Datum und Startzeit ein.");return}setBusy(true);try{const response=await fetch(`/api/admin/courses/${course.id}/sessions/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({startsAt:zonedLocalToIso(`${editRow.date}T${editRow.time}`)})}),result=await response.json();if(!response.ok){notify(result.error);return}setEditing(null);notify(`Einheit ${item.sequence} wurde aktualisiert.`);await load()}catch(error){notify(error instanceof Error?error.message:"Der Termin konnte nicht aktualisiert werden. Prüfe die Verbindung.")}finally{setBusy(false)}}
  async function removeSession(item:Session){if(!confirm(`Einheit ${item.sequence} wirklich löschen? Bereits dokumentierte Anwesenheiten werden revisionssicher archiviert.`))return;setBusy(true);try{const response=await fetch(`/api/admin/courses/${course.id}/sessions/${item.id}`,{method:"DELETE"}),result=await response.json();if(!response.ok){notify(result.error);return}setEditing(null);notify(`Einheit ${item.sequence} wurde gelöscht.${result.attendanceArchived?` ${result.attendanceArchived} Anwesenheitsnachweis(e) wurden archiviert.`:""}`);await load()}catch{notify("Der Termin konnte nicht gelöscht werden. Prüfe die Verbindung.")}finally{setBusy(false)}}
  return <section className="session-planner"><div className="planner-heading"><div><p className="eyebrow">Terminserie</p><h3>{sessions.length} von {course.sessionCount} Terminen angelegt</h3><p>Nummer und Titel entstehen automatisch. Die Endzeit ergibt sich aus {course.durationMinutes} Minuten Kursdauer.</p></div></div>{rows.length?<><details className="bulk-dates"><summary>Termine komma- oder zeilengetrennt einfügen</summary><textarea value={bulk} onChange={event=>setBulk(event.target.value)} placeholder="01.07.2027 18:30, 08.07.2027 18:30"/><button type="button" onClick={importDates}>Termine übernehmen</button></details><form onSubmit={save}><div className="session-date-grid">{rows.map((row,index)=><div key={row.sequence}><b>Einheit {row.sequence}</b><label>Datum<input type="date" value={row.date} onChange={event=>update(index,"date",event.target.value)} required/></label><label>Startzeit<input type="time" value={row.time} onChange={event=>update(index,"time",event.target.value)} required/></label></div>)}</div><button className="primary" disabled={busy}>{busy?"Termine werden gespeichert …":`Alle ${rows.length} Termine anlegen`}</button></form></>:<p className="planner-complete">✓ Für alle Kurseinheiten ist ein Termin angelegt.</p>}{sessions.length>0&&<div className="planned-sessions">{sessions.map(item=>editing===item.id?<div className="session-edit-row" key={item.id}><b>{item.sequence}. Einheit</b><label>Datum<input type="date" value={editRow.date} onChange={event=>setEditRow({...editRow,date:event.target.value})}/></label><label>Startzeit<input type="time" value={editRow.time} onChange={event=>setEditRow({...editRow,time:event.target.value})}/></label><span className="session-actions"><button type="button" disabled={busy} onClick={()=>updateSession(item)}>Speichern</button><button type="button" onClick={()=>setEditing(null)}>Abbrechen</button></span></div>:<div key={item.id}><b>{item.sequence}. Einheit</b><span>{new Date(item.startsAt).toLocaleString("de-DE",{timeZone:appTimeZone(),dateStyle:"medium",timeStyle:"short"})}–{new Date(item.endsAt).toLocaleTimeString("de-DE",{timeZone:appTimeZone(),hour:"2-digit",minute:"2-digit"})} Uhr</span><span className="session-actions"><button type="button" onClick={()=>beginEdit(item)}>Ändern</button><button type="button" className="danger-link" onClick={()=>removeSession(item)}>Löschen</button></span></div>)}</div>}</section>
}
