"use client";
import {FormEvent,useState} from "react";
import {appTimeZone} from "@/lib/app-time";
export type EditableContent={id:string;title:string;kind:string;body:string|null;externalUrl:string|null;status:string;ruleType:string;threshold:number|null;sessionSequence:number|null;contentUpdatedAt:string};
export function AdminContentEditor({items,reload,notify}:{items:EditableContent[];reload:()=>Promise<void>;notify:(text:string)=>void}){
  const [editing,setEditing]=useState<string|null>(null);
  async function save(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget),response=await fetch(`/api/admin/content/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({title:f.get("title"),body:f.get("body")||null,externalUrl:f.get("externalUrl")||null,status:f.get("status"),ruleType:f.get("ruleType"),threshold:Number(f.get("threshold"))||null,sessionSequence:Number(f.get("sessionSequence"))||null})}),result=await response.json();if(!response.ok){notify(result.error);return}setEditing(null);notify("Inhalt wurde aktualisiert.");await reload()}
  async function remove(item:EditableContent){if(!confirm(`„${item.title}“ endgültig löschen? Die Freischaltungen dieses Inhalts werden ebenfalls entfernt.`))return;const response=await fetch(`/api/admin/content/${item.id}`,{method:"DELETE"}),result=await response.json();if(!response.ok){notify(result.error);return}setEditing(null);notify(`„${item.title}“ wurde endgültig gelöscht.`);await reload()}
  return <div className="admin-list edit-list">{items.map(item=>editing===item.id?<form className="admin-form edit-box" onSubmit={e=>save(e,item.id)} key={item.id}><label>Titel<input name="title" defaultValue={item.title} required/></label><label>Text<textarea name="body" defaultValue={item.body||""}/></label><label>Externer Link<input name="externalUrl" type="url" defaultValue={item.externalUrl||""}/></label><div className="form-row"><label>Status<select name="status" defaultValue={item.status}><option value="draft">Entwurf</option><option value="published">Veröffentlicht</option><option value="archived">Archiviert</option></select></label><label>Freischaltung<select name="ruleType" defaultValue={item.ruleType}><option value="immediate">Sofort</option><option value="attendance_count">Nach Teilnahmen</option><option value="session">Nach Einheit</option><option value="completion">Nach Abschluss</option><option value="manual">Manuell</option></select></label></div><div className="form-row"><label>Anzahl<input name="threshold" type="number" min="1" defaultValue={item.threshold||""}/></label><label>Einheit Nr.<input name="sessionSequence" type="number" min="1" defaultValue={item.sessionSequence||""}/></label></div><div className="edit-actions"><button className="primary">Speichern</button><button type="button" onClick={()=>setEditing(null)}>Abbrechen</button><button type="button" className="danger-action" onClick={()=>remove(item)}>Inhalt löschen</button></div></form>:<button className="editable-row" onClick={()=>setEditing(item.id)} key={item.id}><span><b>{item.title}</b><small>{item.kind} · {item.ruleType} · Stand {new Date(item.contentUpdatedAt).toLocaleString("de-DE",{timeZone:appTimeZone()})}</small></span><i>{item.status} · Bearbeiten</i></button>)}</div>
}
