"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useState} from "react";
import {messageOf,requestJson} from "./client-api";
import {appTimeZone} from "@/lib/app-time";
type Job={id:string;kind:string;recipient:string;status:"queued"|"processing"|"sent"|"failed";attempts:number;maxAttempts:number;lastError:string|null;createdAt:string;sentAt:string|null;codeHint:string|null};
type Result={jobs:Job[];counts:{status:string;count:number}[]};
const labels={course_invitation:"Kurseinladung",batch_summary:"Admin-Versandbericht",admin_notification:"Admin-Benachrichtigung",system_alert:"Systemwarnung"} as Record<string,string>;
export function AdminMailQueue(){const [data,setData]=useState<Result>({jobs:[],counts:[]}),[notice,setNotice]=useState("");async function load(){try{setData(await requestJson<Result>("/api/admin/mail-queue"))}catch(error){setNotice(messageOf(error))}}useEffect(()=>{void load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[]);async function retry(id:string){try{const result=await requestJson<{message:string}>("/api/admin/mail-queue",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id})});setNotice(result.message);await load()}catch(error){setNotice(messageOf(error))}}const count=(status:string)=>data.counts.find(item=>item.status===status)?.count||0;return <article className="panel mail-queue-panel"><div className="panel-title"><div><small>ZUVERLÄSSIGER HINTERGRUNDVERSAND</small><h2>Mailwarteschlange</h2><p>Einladungen werden auch nach dem Schließen des Browsers weiterverarbeitet.</p></div><button onClick={load}>Aktualisieren</button></div><div className="queue-metrics"><span><b>{count("queued")+count("processing")}</b> offen</span><span><b>{count("sent")}</b> versendet</span><span className={count("failed")?"bad":""}><b>{count("failed")}</b> fehlgeschlagen</span></div>{notice&&<p className="form-feedback" role="status">{notice}</p>}<div className="mail-job-list">{data.jobs.map(job=><article key={job.id}><span className={`status-dot ${job.status}`}/><div><b>{labels[job.kind]||job.kind}</b><small>{job.recipient}{job.codeHint?` · Code ••••-${job.codeHint}`:""}</small><small>{new Date(job.sentAt||job.createdAt).toLocaleString("de-DE",{timeZone:appTimeZone()})} · Versuch {job.attempts}/{job.maxAttempts}</small>{job.lastError&&<em>{job.lastError}</em>}</div><strong>{job.status==="sent"?"Versendet":job.status==="failed"&&job.attempts>=job.maxAttempts?"Fehlgeschlagen":job.status==="processing"?"Wird versendet":"Vorgemerkt"}</strong>{job.status==="failed"&&job.attempts>=job.maxAttempts&&<button onClick={()=>retry(job.id)}>Erneut senden</button>}</article>)}</div>{!data.jobs.length&&<p>Noch keine E-Mails vorgemerkt.</p>}</article>}
