"use client";
import { FormEvent } from "react";
type User={id:string;email:string;role:string;firstName:string;lastName:string;status:string;courseCount:number};
export function AdminUsers({users,reload,notify}:{users:User[];reload:()=>Promise<void>;notify:(text:string)=>void}){
  const participants=users.filter(user=>user.role==="user"&&user.status==="active");
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),response=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f.entries()))}),result=await response.json();if(!response.ok){notify(result.error);return}form.reset();notify("Administrationskonto wurde angelegt. Beim ersten Öffnen des Adminbereichs muss 2FA eingerichtet werden.");await reload()}
  async function toggle(user:User){const status=user.status==="active"?"blocked":"active",response=await fetch(`/api/admin/users/${user.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})}),result=await response.json();if(!response.ok){notify(result.error);return}notify(status==="active"?"Konto wurde reaktiviert.":"Konto wurde gesperrt.");await reload()}
  async function merge(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,response=await fetch("/api/admin/users/merge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form).entries()))}),result=await response.json();if(!response.ok){notify(result.error);return}form.reset();notify("Konten wurden zusammengeführt. Das Quellkonto kann nicht mehr verwendet werden.");await reload()}
  return <><div className="admin-workspace"><article className="panel"><small>ADMIN HINZUFÜGEN</small><form className="admin-form" onSubmit={create}><div className="form-row"><label>Vorname<input name="firstName" required/></label><label>Nachname<input name="lastName" required/></label></div><label>E-Mail-Adresse<input name="email" type="email" required/></label><label>Sicheres Startpasswort <small>mindestens 12 Zeichen; persönlich übermitteln</small><input name="password" type="password" minLength={12} required/></label><button className="primary">Admin anlegen</button></form></article><article className="panel"><small>ALLE KONTEN</small><div className="account-list">{users.map(user=><div key={user.id}><div><b>{user.firstName} {user.lastName}</b><small>{user.email} · {user.role==="admin"?"Admin":`${user.courseCount} Kurs(e)`}</small></div><span className={`account-status ${user.status}`}>{user.status==="active"?"Aktiv":user.status==="merged"?"Zusammengeführt":"Gesperrt"}</span>{user.status!=="merged"&&<button onClick={()=>toggle(user)}>{user.status==="active"?"Sperren":"Reaktivieren"}</button>}</div>)}</div></article></div><article className="panel merge-panel"><small>DOPPELTE KONTEN ZUSAMMENFÜHREN</small><p>Alle Kurse, Anwesenheiten und Freischaltungen werden in das Zielkonto übernommen. Das Quellkonto wird dauerhaft stillgelegt. Admin-Konten sind ausgeschlossen.</p><form className="admin-form" onSubmit={merge}><div className="form-row"><label>Quellkonto<select name="sourceUserId" required><option value="">Auswählen</option>{participants.map(user=><option value={user.id} key={user.id}>{user.email}</option>)}</select></label><label>Zielkonto<select name="targetUserId" required><option value="">Auswählen</option>{participants.map(user=><option value={user.id} key={user.id}>{user.email}</option>)}</select></label></div><label>Zur Bestätigung „KONTEN ZUSAMMENFÜHREN“ eingeben<input name="confirmation" pattern="KONTEN ZUSAMMENFÜHREN" required/></label><button className="merge-button">Konten endgültig zusammenführen</button></form></article></>}
