"use client";
/* Event images are authenticated media responses and are intentionally rendered directly. */
/* eslint-disable @next/next/no-img-element */
import { FormEvent,useCallback,useEffect,useState } from "react";

type EventItem={id:string;title:string;description:string;startsAt:string;endsAt:string;location:string|null;navigationUrl:string|null;shopUrl:string|null;mediaId:string|null;status:string};
const local=(value:string)=>new Date(value).toISOString().slice(0,16);

async function uploadImage(file:FormDataEntryValue|null){
  if(!(file instanceof File)||!file.size)return undefined;
  const data=new FormData();data.set("file",file);
  const response=await fetch("/api/admin/media",{method:"POST",body:data}),result=await response.json();
  if(!response.ok)throw new Error(result.error||"Das Titelbild konnte nicht hochgeladen werden.");
  return result.id as string;
}

export function AdminEvents(){
  const [events,setEvents]=useState<EventItem[]>([]),[editing,setEditing]=useState<string|null>(null),[notice,setNotice]=useState(""),[,setBusy]=useState(false);
  const load=useCallback(()=>fetch("/api/admin/events").then(r=>r.json()).then(x=>setEvents(x.events||[])),[]);
  useEffect(()=>{load()},[load]);
  async function values(form:HTMLFormElement,currentMediaId?:string|null){const f=new FormData(form),start=String(f.get("startsAt")),end=String(f.get("endsAt"));if(!start||!end)throw new Error("Bitte Beginn und Ende vollständig angeben.");if(new Date(end)<=new Date(start))throw new Error("Das Ende muss nach dem Beginn liegen.");const uploaded=await uploadImage(f.get("image"));return {title:String(f.get("title")||"").trim(),description:String(f.get("description")||""),startsAt:new Date(start).toISOString(),endsAt:new Date(end).toISOString(),location:f.get("location")||null,navigationUrl:f.get("navigationUrl")||null,shopUrl:f.get("shopUrl")||null,mediaId:uploaded??currentMediaId??null,status:f.get("status")||"published"}}
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setNotice("");try{const r=await fetch("/api/admin/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(await values(form))}),x=await r.json();if(!r.ok){const field=x.field&&form.elements.namedItem(String(x.field));if(field instanceof HTMLElement)field.focus();throw new Error(x.error||"Die Veranstaltung konnte nicht gespeichert werden.")}form.reset();setNotice("Veranstaltung wurde erfolgreich veröffentlicht.");await load()}catch(error){setNotice((error as Error).message)}finally{setBusy(false)}}
  async function update(e:FormEvent<HTMLFormElement>,event:EventItem){e.preventDefault();try{const r=await fetch(`/api/admin/events/${event.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(await values(e.currentTarget,event.mediaId))}),x=await r.json();if(!r.ok)throw new Error(x.error);setEditing(null);setNotice("Veranstaltung aktualisiert.");await load()}catch(error){setNotice((error as Error).message)}}
  async function setStatus(event:EventItem,status:"published"|"archived"){const r=await fetch(`/api/admin/events/${event.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})}),x=await r.json();if(!r.ok){setNotice(x.error);return}setEditing(null);setNotice(status==="archived"?"Veranstaltung wurde archiviert.":"Veranstaltung wurde wiederhergestellt.");await load()}
  async function remove(event:EventItem){if(window.prompt(`Diese Veranstaltung wird endgültig gelöscht.\n\nGib zur Bestätigung den Titel ein:\n${event.title}`)!==event.title){setNotice("Löschen abgebrochen: Der Titel stimmte nicht überein.");return}const r=await fetch(`/api/admin/events/${event.id}`,{method:"DELETE"}),x=await r.json();if(!r.ok){setNotice(x.error);return}setEditing(null);setNotice("Veranstaltung wurde endgültig gelöscht.");await load()}
  const active=events.filter(event=>event.status!=="archived"),archived=events.filter(event=>event.status==="archived");
  const formFields=(event?:EventItem)=><><label>Titel<input name="title" defaultValue={event?.title} required/></label><label>Beschreibung<textarea name="description" defaultValue={event?.description}/></label><label>Titelbild <small>optional · JPEG, PNG oder WebP · maximal 5 MB</small><input name="image" type="file" accept="image/jpeg,image/png,image/webp"/>{event?.mediaId&&<img className="event-image-preview" src={`/api/media/${event.mediaId}`} alt="Aktuelles Titelbild"/>}</label><div className="form-row"><label>Beginn<input name="startsAt" type="datetime-local" defaultValue={event?local(event.startsAt):undefined} required/></label><label>Ende<input name="endsAt" type="datetime-local" defaultValue={event?local(event.endsAt):undefined} required/></label></div><label>Ort<input name="location" defaultValue={event?.location||""}/></label><label>Navigationslink<input name="navigationUrl" type="url" defaultValue={event?.navigationUrl||""}/></label><label>Shop-/Buchungslink<input name="shopUrl" type="url" defaultValue={event?.shopUrl||""}/></label></>;
  return <><div className="admin-workspace"><article className="panel"><small>VERANSTALTUNG ANLEGEN</small><form className="admin-form" onSubmit={create}>{formFields()}<input name="status" type="hidden" value="published"/><button className="primary">Veröffentlichen</button>{notice&&<p className="form-feedback">{notice}</p>}</form></article><article className="panel"><small>AKTIVE VERANSTALTUNGEN</small><div className="admin-list edit-list">{active.map(event=>editing===event.id?<form className="admin-form edit-box" key={event.id} onSubmit={e=>update(e,event)}>{formFields(event)}<div className="form-row"><button className="primary">Speichern</button><button type="button" onClick={()=>setEditing(null)}>Abbrechen</button></div><div className="destructive-actions"><button type="button" onClick={()=>setStatus(event,"archived")}>Archivieren</button><button type="button" className="danger-action" onClick={()=>remove(event)}>Endgültig löschen</button></div></form>:<button className="editable-row" onClick={()=>setEditing(event.id)} key={event.id}>{event.mediaId&&<img src={`/api/media/${event.mediaId}`} alt=""/>}<span><b>{event.title}</b><small>{new Date(event.startsAt).toLocaleString("de-DE")} · {event.location||"Ort offen"}</small></span><i>Bearbeiten</i></button>)}{!active.length&&<p>Noch keine aktive Veranstaltung.</p>}</div></article></div>{archived.length>0&&<details className="panel archive-accordion"><summary>Archivierte Veranstaltungen <span>{archived.length}</span></summary><div className="admin-list">{archived.map(event=><div className="archived-row" key={event.id}>{event.mediaId&&<img src={`/api/media/${event.mediaId}`} alt=""/>}<span><b>{event.title}</b><small>{new Date(event.startsAt).toLocaleString("de-DE")}</small></span><div><button onClick={()=>setStatus(event,"published")}>Wiederherstellen</button><button className="danger-action" onClick={()=>remove(event)}>Endgültig löschen</button></div></div>)}</div></details>}</>;
}
