"use client";
/* The local SVG logo is served directly and does not benefit from raster optimization. */
/* eslint-disable @next/next/no-img-element */

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AdminTwoFactor } from "./admin-two-factor";
import { AdminUsers } from "./admin-users";
import { AdminEvents } from "./admin-events";
import {AdminAttendanceWorkspace} from "./admin-attendance-workspace";
import {AdminAuditLog} from "./admin-audit-log";
import { AdminSmtp } from "./admin-smtp";
import {AdminMailQueue} from "./admin-mail-queue";
import {AdminSystem} from "./admin-system";
import { AdminPrivacy } from "./admin-privacy";
import { AdminAppearance } from "./admin-appearance";
import { AdminPush } from "./admin-push";
import { AdminUpdate } from "./admin-update";
import { AdminCourseEdit } from "./admin-course-edit";
import { AdminContentEditor,EditableContent } from "./admin-content-editor";
import { AdminRetention } from "./admin-retention";
import { requestJson } from "./client-api";
import { useAdminTooltips } from "./use-admin-tooltips";
import { useAdminFormUx } from "./use-admin-form-ux";
import { useAdminSubmitLock } from "./use-admin-submit-lock";
import { AdminAddressFields } from "./admin-address-fields";

type Course={id:string;title:string;description:string;sessionCount:number;durationMinutes:number;startsAt:string|null;endsAt:string|null;location:string|null;navigationUrl:string|null;status:string;treeVariant:string};
type User={id:string;email:string;role:string;firstName:string;lastName:string;status:string;courseCount:number};
type Session={id:string;sequence:number;title:string;startsAt:string;endsAt:string;location:string|null};
type Roster={id:string;firstName:string;lastName:string;email:string;attendedCount:number;completedAt:string|null};
type QueuedAttendance={userId:string;sessionId:string;source:"list";queuedAt:string};
type Tab="overview"|"courses"|"codes"|"attendance"|"audit"|"content"|"events"|"users"|"appearance"|"communication"|"push"|"privacy"|"retention"|"system"|"security";
type ApiResult={courses:Course[];users:User[];sessions:Session[];roster:Roster[];items:EditableContent[];codes:{code:string;assignedEmail:string|null}[];delivery?:{requested:boolean;queued:number;unassigned:number};id?:string};

async function api(url:string,options?:RequestInit){if(url==="/api/admin/media"&&options?.body instanceof FormData){const file=options.body.get("file");if(file instanceof File&&file.type.startsWith("video/"))options={method:"POST",headers:{"content-type":"application/octet-stream","x-file-name":encodeURIComponent(file.name),"x-file-type":file.type,"x-file-size":String(file.size)},body:file}}return requestJson<ApiResult>(url,options)}
const json=(body:unknown)=>({method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});

export function AdminConsole({close,admin,requireSecurity=false}:{close:()=>void;admin:{firstName:string;lastName:string};requireSecurity?:boolean}){
  useAdminTooltips();
  useAdminFormUx();
  useAdminSubmitLock();
  const [tab,setTab]=useState<Tab>(requireSecurity?"security":"overview"),[courses,setCourses]=useState<Course[]>([]),[users,setUsers]=useState<User[]>([]),[selected,setSelected]=useState(""),[sessions,setSessions]=useState<Session[]>([]),[roster,setRoster]=useState<Roster[]>([]),[contents,setContents]=useState<EditableContent[]>([]),[codes,setCodes]=useState<{code:string;assignedEmail:string|null}[]>([]),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{if(requireSecurity)return;try{const [c,u]=await Promise.all([api("/api/admin/courses"),api("/api/admin/users")]);setCourses(c.courses);setUsers(u.users);const firstActive=c.courses.find(course=>course.status!=="archived");if(!selected&&firstActive)setSelected(firstActive.id);}catch(e){setNotice((e as Error).message)}},[selected,requireSecurity]);
  // Data arrives asynchronously; these effects synchronize the selected server records.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{load()},[load]);
  useEffect(()=>{if(requireSecurity||!selected)return;Promise.all([api(`/api/admin/courses/${selected}/sessions`),api(`/api/admin/courses/${selected}/roster`),api(`/api/admin/content?courseId=${selected}`)]).then(([s,r,c])=>{setSessions(s.sessions);setRoster(r.roster);setContents(c.items)}).catch(e=>setNotice(e.message));},[selected,requireSecurity]);
  useEffect(()=>{async function sync(){const queued=JSON.parse(localStorage.getItem("kraftbaum_attendance_queue")||"[]") as QueuedAttendance[];if(!queued.length)return;const remaining:QueuedAttendance[]=[];for(const item of queued){try{const response=await fetch("/api/admin/attendance",json(item));if(!response.ok)remaining.push(item)}catch{remaining.push(item)}}localStorage.setItem("kraftbaum_attendance_queue",JSON.stringify(remaining));if(!remaining.length){setNotice("Offline erfasste Anwesenheiten wurden synchronisiert.");load()}}window.addEventListener("online",sync);if(navigator.onLine)sync();return()=>window.removeEventListener("online",sync)},[load]);
  async function submitCourse(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{await api("/api/admin/courses",json({title:f.get("title"),description:f.get("description"),sessionCount:Number(f.get("sessionCount")),durationMinutes:Number(f.get("durationMinutes")),location:f.get("location"),navigationUrl:f.get("navigationUrl"),status:"published"}));form.reset();setNotice("Kurs wurde angelegt.");await load()}catch(err){setNotice((err as Error).message)}}
  async function submitSession(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{await api(`/api/admin/courses/${selected}/sessions`,json({sequence:Number(f.get("sequence")),title:f.get("title"),startsAt:new Date(String(f.get("startsAt"))).toISOString(),endsAt:new Date(String(f.get("endsAt"))).toISOString(),location:f.get("location")||undefined,navigationUrl:f.get("navigationUrl")||undefined}));form.reset();setNotice("Termin wurde angelegt.");const result=await api(`/api/admin/courses/${selected}/sessions`);setSessions(result.sessions)}catch(err){setNotice((err as Error).message)}}
  async function submitCodes(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const emails=String(f.get("emails")||"").split(/[\n,;]/).map(x=>x.trim()).filter(Boolean),sendInvitations=f.get("sendInvitations")==="on";const result=await api("/api/admin/codes",json({courseId:selected,type:f.get("type"),count:Number(f.get("count")),assignedEmails:emails,sendInvitations}));setCodes(result.codes);const delivery=result.delivery;setNotice(delivery?.requested?`${result.codes.length} Codes erzeugt · ${delivery.queued} Einladungen sicher zum Versand vorgemerkt${delivery.unassigned?` · ${delivery.unassigned} ohne E-Mail-Zuordnung`:""}. Der Versand läuft unabhängig vom Browser weiter.`:`${result.codes.length} Codes wurden erzeugt. Es wurden keine persönlichen Einladungen vorgemerkt. Die Codes sind nur jetzt vollständig sichtbar.`)}catch(err){setNotice((err as Error).message)}}
  function exportCodes(){const quote=(value:string)=>`"${value.replaceAll('"','""')}"`,rows=[["Code","Zugeordnete E-Mail","Kurs"],...codes.map(item=>[item.code,item.assignedEmail||"",selectedCourse?.title||""])],blob=new Blob(["\ufeff"+rows.map(row=>row.map(quote).join(";")).join("\r\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`kraftbaum-codes-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)}
  async function mark(userId:string,sessionId:string){const item:QueuedAttendance={userId,sessionId,source:"list",queuedAt:new Date().toISOString()};if(!navigator.onLine){const queued=JSON.parse(localStorage.getItem("kraftbaum_attendance_queue")||"[]") as QueuedAttendance[];localStorage.setItem("kraftbaum_attendance_queue",JSON.stringify([...queued.filter(x=>x.userId!==userId||x.sessionId!==sessionId),item]));setNotice("Offline gespeichert. Die Anwesenheit wird bei der nächsten Verbindung synchronisiert.");return}try{await api("/api/admin/attendance",json(item));setNotice("Anwesenheit gespeichert.");const r=await api(`/api/admin/courses/${selected}/roster`);setRoster(r.roster)}catch(err){setNotice((err as Error).message)}}
  async function submitContent(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),kind=String(f.get("kind"));try{let assetPath:undefined|string;const file=f.get("file");if(file instanceof File&&file.size){const upload=new FormData();upload.set("file",file);const saved=await api("/api/admin/media",{method:"POST",body:upload});assetPath=saved.id}await api("/api/admin/content",json({courseId:selected,title:f.get("title"),kind,body:String(f.get("body")||"")||undefined,externalUrl:String(f.get("externalUrl")||"")||undefined,assetPath,status:f.get("status"),ruleType:f.get("ruleType"),threshold:Number(f.get("threshold"))||undefined,sessionSequence:Number(f.get("sessionSequence"))||undefined}));form.reset();setNotice("Inhalt wurde gespeichert.");const result=await api(`/api/admin/content?courseId=${selected}`);setContents(result.items)}catch(err){setNotice((err as Error).message)}}
  async function archiveCourse(){if(selectedCourse)await setCourseStatus(selectedCourse,"archived")}
  async function setCourseStatus(course:Course,status:"published"|"archived"){try{await api(`/api/admin/courses/${course.id}`,{...json({status}),method:"PATCH"});if(selected===course.id&&status==="archived")setSelected("");setNotice(status==="archived"?"Kurs wurde archiviert.":"Kurs wurde wiederhergestellt.");await load()}catch(err){setNotice((err as Error).message)}}
  async function deleteCourse(course:Course){if(window.prompt(`Dieser Vorgang löscht den Kurs sowie Termine, Codes und Freischaltungen endgültig. Gesetzlich aufzubewahrende Anwesenheitsnachweise bleiben pseudonymisiert im Nachweisarchiv.\n\nGib zur Bestätigung den Kurstitel ein:\n${course.title}`)!==course.title){setNotice("Löschen abgebrochen: Der Kurstitel stimmte nicht überein.");requestAnimationFrame(()=>document.querySelector(".admin-notice")?.scrollIntoView({behavior:"smooth",block:"center"}));return}setNotice("Kurs wird endgültig gelöscht …");try{await api(`/api/admin/courses/${course.id}`,{method:"DELETE"});if(selected===course.id)setSelected("");setNotice(`„${course.title}“ wurde endgültig gelöscht. Aufbewahrungspflichtige Anwesenheitsnachweise wurden sicher archiviert.`);await load()}catch(err){setNotice(`Kurs konnte nicht gelöscht werden: ${(err as Error).message}`)}finally{requestAnimationFrame(()=>document.querySelector(".admin-notice")?.scrollIntoView({behavior:"smooth",block:"center"}))}}
  const selectedCourse=courses.find(c=>c.id===selected);
  const activeCourses=courses.filter(course=>course.status!=="archived"),archivedCourses=courses.filter(course=>course.status==="archived");
  const navigation=([['overview','Übersicht'],['courses','Kurse & Termine'],['codes','Codes'],['attendance','Anwesenheit'],['audit','Auditprotokoll'],['content','Inhalte'],['events','Events'],['users','Teilnehmer'],['appearance','Optik'],['communication','E-Mail'],['push','Push'],['privacy','Datenschutz'],['retention','Fristen'],['system','System & Backups'],['security','Sicherheit']] as [Tab,string][]).filter(([id])=>!requireSecurity||id==="security"||id==="communication");
  return <main className="admin-page real-admin"><aside><button className="brand admin-brand" onClick={close}><img className="brand-logo" src="/logo-kraftbaum.svg" alt=""/><span><b>STÄRKE DEINE MITTE</b><small>{admin.firstName} {admin.lastName} · ADMIN</small></span></button><nav>{navigation.map(([id,label])=><button className={tab===id?"selected":""} onClick={()=>setTab(id)} key={id}>{label}<span>›</span></button>)}</nav><button className="back" onClick={close}>← Teilnehmeransicht</button></aside><section className="admin-main"><div className="admin-mobile-navigation"><button type="button" onClick={close}>← Teilnehmeransicht</button><label>Adminbereich<select aria-label="Adminbereich auswählen" value={tab} onChange={event=>setTab(event.target.value as Tab)}>{navigation.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label></div><header><div><p className="eyebrow">Administration</p><h1>{tab==="overview"?`Guten Abend, ${admin.firstName}.`:tab==="courses"?"Kurse & Termine":tab==="codes"?"Zugangscodes":tab==="attendance"?"Anwesenheit":tab==="content"?"Kursinhalte":tab==="events"?"Veranstaltungen":tab==="appearance"?"Erscheinungsbild":tab==="communication"?"E-Mail & Support":tab==="push"?"Push-Benachrichtigungen":tab==="privacy"?"Datenschutz & Recht":tab==="retention"?"Aufbewahrung & Löschung":tab==="system"?"System & Backups":tab==="security"?"Sicherheit":"Teilnehmer"}</h1>{requireSecurity&&<p>Schließe zuerst die Admin-Sicherheit ab. Für E-Mail-Codes kannst du vorher unter „E-Mail“ den SMTP-Versand einrichten.</p>}</div><button className="admin-avatar" aria-label={`Angemeldet als ${admin.firstName} ${admin.lastName}`}>{admin.firstName[0]}{admin.lastName[0]}</button></header>{notice&&<button className="admin-notice" onClick={()=>setNotice("")}>{notice} ×</button>}
  {tab==="overview"&&<><div className="metric-grid"><article><span>AKTIVE TEILNEHMER</span><b>{users.filter(u=>u.role==="user"&&u.status==="active").length}</b><small>registrierte Konten</small></article><article><span>KURSE</span><b>{activeCourses.length}</b><small>{courses.filter(c=>c.status==="published").length} veröffentlicht</small></article><article><span>TERMINE</span><b>{sessions.length}</b><small>im gewählten Kurs</small></article><article><span>APP-STATUS</span><b className="healthy">● Online</b><small>Revision und Updates im Footer</small></article></div><article className="panel"><div className="panel-title"><div><small>AKTUELLE KURSE</small><h2>Deine Kursdurchläufe</h2></div><button className="primary" onClick={()=>setTab("courses")}>Kurs anlegen</button></div><div className="admin-list">{activeCourses.length?activeCourses.map(c=><button onClick={()=>{setSelected(c.id);setTab("courses")}} key={c.id}><div><b>{c.title}</b><small>{c.sessionCount} × {c.durationMinutes} Minuten · {c.location||"Ort offen"}</small></div><span>{c.status} ›</span></button>):<p>Noch kein Kurs angelegt.</p>}</div></article></>}
  {tab==="courses"&&<><div className="admin-workspace"><article className="panel"><small>NEUER KURSDURCHLAUF</small><form className="admin-form" onSubmit={submitCourse}><label>Titel<input name="title" required placeholder="Beginner Herbst 2026"/></label><label>Beschreibung<textarea name="description"/></label><div className="form-row"><label>Einheiten<input name="sessionCount" type="number" min="1" defaultValue="8" required/></label><label>Minuten je Einheit<input name="durationMinutes" type="number" min="15" defaultValue="90" required/></label></div><AdminAddressFields/><button className="primary">Kurs anlegen</button></form></article><article className="panel"><small>TERMINE VERWALTEN</small><select className="admin-select" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Kurs wählen</option>{activeCourses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select>{selected&&<><AdminCourseEdit course={selectedCourse!} reload={load} notify={setNotice}/><div className="destructive-actions"><button className="archive-action" onClick={archiveCourse}>Gewählten Kurs archivieren</button><button className="danger-action" onClick={()=>deleteCourse(selectedCourse!)}>Kurs endgültig löschen</button></div><form className="admin-form compact" onSubmit={submitSession}><div className="form-row"><label>Nr.<input name="sequence" type="number" min="1" required/></label><label>Titel<input name="title" required/></label></div><div className="form-row"><label>Beginn<input name="startsAt" type="datetime-local" required/></label><label>Ende<input name="endsAt" type="datetime-local" required/></label></div><label>Ort<input name="location" defaultValue={selectedCourse?.location||""}/></label><label>Navigationslink<input name="navigationUrl" type="url" defaultValue={selectedCourse?.navigationUrl||""}/></label><button className="primary">Termin hinzufügen</button></form><div className="admin-list">{sessions.map(s=><div className="list-row" key={s.id}><b>{s.sequence}. {s.title}</b><small>{new Date(s.startsAt).toLocaleString("de-DE")}</small></div>)}</div></>}</article></div>{archivedCourses.length>0&&<details className="panel archive-accordion"><summary>Archivierte Kurse <span>{archivedCourses.length}</span></summary><div className="admin-list">{archivedCourses.map(course=><div className="archived-row" key={course.id}><span><b>{course.title}</b><small>{course.sessionCount} × {course.durationMinutes} Minuten</small></span><div><button onClick={()=>setCourseStatus(course,"published")}>Wiederherstellen</button><button className="danger-action" onClick={()=>deleteCourse(course)}>Endgültig löschen</button></div></div>)}</div></details>}</>}
  {tab==="codes"&&<div className="admin-workspace"><article className="panel"><small>CODEPAKET ERZEUGEN</small><form className="admin-form" onSubmit={submitCodes}><label>Kurs<select name="courseId" value={selected} onChange={e=>setSelected(e.target.value)} required><option value="">Kurs wählen</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label><span className="field-title">Codetyp <button type="button" className="admin-help field-help" data-help="Präsenzkurs · gestaffelt: Inhalte wachsen mit den dokumentierten Teilnahmen. Vollzugang: Der gesamte Kursinhalt wird sofort freigeschaltet. Event: Zugang für eine besondere Einzelveranstaltung; eignet sich für Erinnerungen und Eventinhalte." aria-label="Codetypen erklären" aria-expanded="false" title="Die drei Codetypen im Vergleich">?</button></span><select name="type"><option value="attendance" title="Freischaltung wächst schrittweise mit den dokumentierten Kursteilnahmen.">Präsenzkurs · gestaffelt</option><option value="full" title="Schaltet alle Inhalte des ausgewählten Kurses sofort frei.">Vollzugang</option><option value="event" title="Zugang zu einer besonderen Einzelveranstaltung und ihren Eventinhalten.">Event</option></select></label><label>Anzahl<input name="count" type="number" min="1" max="500" defaultValue="8" required/></label><label>E-Mail-Zuordnung <small>optional, eine Adresse pro Zeile</small><textarea name="emails" placeholder="anna@example.de"/></label><label className="check code-mail-choice"><input name="sendInvitations" type="checkbox" aria-label="Persönliche Einladungen jetzt versenden"/><span><b>Persönliche Einladungen jetzt versenden</b><small>Nur Adressen aus der Liste erhalten jeweils ihren eigenen Code. Ohne Haken werden ausschließlich die Codes erzeugt. Der Admin erhält in beiden Fällen eine Sammel-E-Mail.</small></span></label><button className="primary">Codes sicher erzeugen</button></form></article><article className="panel code-results printable-codes"><small>EINMALIGE AUSGABE · {selectedCourse?.title}</small>{codes.length?<><div className="code-actions"><button onClick={exportCodes}>CSV herunterladen</button><button onClick={()=>window.print()}>Als PDF drucken</button></div>{codes.map(c=><div key={c.code}><code>{c.code}</code><span>{c.assignedEmail||"frei"}</span><button onClick={()=>navigator.clipboard.writeText(c.code)}>Kopieren</button></div>)}</>:<p>Neu erzeugte Codes werden hier einmalig angezeigt.</p>}</article></div>}
  {tab==="attendance"&&<article className="panel"><div className="panel-title"><div><small>DREI EINFACHE WEGE</small><h2>{selectedCourse?.title||"Kurs wählen"}</h2><p>Persönlich per Liste, mit individuellem QR oder als Selbst-Check-in für größere Gruppen.</p></div><select className="admin-select inline" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Kurs wählen</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></div>{sessions.length>0&&<AdminAttendanceWorkspace sessions={sessions} roster={roster} onMark={mark}/>} {!sessions.length&&<p>Lege zunächst Termine für diesen Kurs an.</p>}</article>}
  {tab==="audit"&&<AdminAuditLog/>}
  {tab==="content"&&<div className="admin-workspace"><article className="panel"><small>INHALT ANLEGEN</small><form className="admin-form" onSubmit={submitContent}><label>Kurs<select value={selected} onChange={e=>setSelected(e.target.value)} required><option value="">Kurs wählen</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label>Titel<input name="title" required/></label><div className="form-row"><label>Art<select name="kind"><option value="text">Text</option><option value="image">Bild</option><option value="pdf">PDF</option><option value="video">Eigenes Video</option><option value="youtube">YouTube</option><option value="vimeo">Vimeo</option><option value="link">Link</option></select></label><label>Status<select name="status"><option value="published">Veröffentlicht</option><option value="draft">Entwurf</option></select></label></div><label>Text / Beschreibung<textarea name="body"/></label><label>Externer Link<input name="externalUrl" type="url" placeholder="https://…"/></label><label>Datei <small>Bilder 5 MB · PDF 20 MB · Video 5 GB</small><input name="file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf,video/mp4,video/webm"/></label><label>Freischaltung<select name="ruleType"><option value="immediate">Sofort</option><option value="attendance_count">Nach Anzahl Teilnahmen</option><option value="session">Nach bestimmter Einheit</option><option value="completion">Nach Kursabschluss</option><option value="manual">Nur manuell</option></select></label><div className="form-row"><label>Anzahl Teilnahmen<input name="threshold" type="number" min="1"/></label><label>Einheit Nr.<input name="sessionSequence" type="number" min="1"/></label></div><button className="primary">Inhalt speichern</button></form></article><article className="panel"><small>INHALTE IM KURS</small><AdminContentEditor items={contents} reload={async()=>{const result=await api(`/api/admin/content?courseId=${selected}`);setContents(result.items)}} notify={setNotice}/>{!contents.length&&<p>Noch keine Inhalte angelegt.</p>}</article></div>}
  {tab==="users"&&<AdminUsers users={users} reload={load} notify={setNotice}/>}
  {tab==="events"&&<AdminEvents/>}
  {tab==="security"&&<AdminTwoFactor/>}
  {tab==="communication"&&<div className="admin-section-stack"><AdminSmtp/><AdminMailQueue/></div>}
  {tab==="system"&&<AdminSystem/>}
  {tab==="privacy"&&<AdminPrivacy/>}
  {tab==="appearance"&&<AdminAppearance/>}
  {tab==="push"&&<AdminPush/>}
  {tab==="retention"&&<AdminRetention/>}
</section>{!requireSecurity&&<footer className="admin-footer"><AdminUpdate/></footer>}</main>;
}
