"use client";
/* eslint-disable @next/next/no-img-element */
import { ChangeEvent,FormEvent,useEffect,useRef,useState } from "react";
import { DEFAULT_GROWTH_MESSAGES,normalizeGrowthMessages } from "@/lib/growth-messages";

type Appearance={figureMediaId:string|null;growthMediaIds:Array<string|null>;growthMessages:string[]};
const empty:Appearance={figureMediaId:null,growthMediaIds:Array(9).fill(null),growthMessages:[...DEFAULT_GROWTH_MESSAGES]};
const labels=["Samen","Erster Trieb","Junge Pflanze","Zwei Äste","Vier Äste","Feine Zweige","Mehr Blätter","Blüten","Rote Äpfel"];

export function AdminAppearance(){
  const [appearance,setAppearance]=useState<Appearance>(empty),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const current=useRef<Appearance>(empty);
  function apply(next:Appearance){current.current=next;setAppearance(next)}
  useEffect(()=>{fetch("/api/admin/settings/appearance").then(r=>r.json()).then(value=>apply({figureMediaId:value.figureMediaId||null,growthMediaIds:Array.from({length:9},(_,i)=>value.growthMediaIds?.[i]||null),growthMessages:normalizeGrowthMessages(value.growthMessages)})).catch(()=>setNotice("Die Darstellung konnte nicht geladen werden."))},[]);
  async function save(next:Appearance){const response=await fetch("/api/admin/settings/appearance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(next)}),result=await response.json().catch(()=>({error:"Der Server hat keine gültige Antwort geliefert."}));if(!response.ok)throw new Error(result.error||"Die Darstellung konnte nicht gespeichert werden.");apply(next)}
  async function uploadFile(file:File){const upload=new FormData();upload.set("file",file);const response=await fetch("/api/admin/media",{method:"POST",body:upload}),result=await response.json().catch(()=>({error:"Der Server hat keine gültige Antwort geliefert."}));if(!response.ok)throw new Error(result.error||"Das Bild konnte nicht hochgeladen werden.");return result.id as string}
  async function uploadFigure(e:FormEvent<HTMLFormElement>){e.preventDefault();try{const file=new FormData(e.currentTarget).get("file");if(!(file instanceof File)||!file.size)return;const id=await uploadFile(file);await save({...appearance,figureMediaId:id});setNotice("Figur gespeichert. Sie erscheint ab sofort am Kraftbaum.")}catch(error){setNotice(error instanceof Error?error.message:"Upload fehlgeschlagen.")}}
  async function uploadStage(stage:number,file:File){if(busy)return;setBusy(true);setNotice(`Stufe ${stage} wird hochgeladen …`);try{const id=await uploadFile(file),growthMediaIds=[...current.current.growthMediaIds];growthMediaIds[stage]=id;await save({...current.current,growthMediaIds});setNotice(`Wachstumsstufe ${stage} wurde gespeichert.`)}catch(error){setNotice(error instanceof Error?error.message:"Upload fehlgeschlagen.")}finally{setBusy(false)}}
  async function uploadAll(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files||[]);event.target.value="";if(!files.length||busy)return;setBusy(true);try{const numbered=files.map(file=>({file,number:Number(file.name.match(/(\d+)/)?.[1])})).filter(item=>item.number>=1&&item.number<=9).sort((a,b)=>a.number-b.number);if(numbered.length!==9||new Set(numbered.map(item=>item.number)).size!==9)throw new Error("Bitte wähle genau die neun Dateien mit den Nummern 1 bis 9 aus.");const growthMediaIds=[...current.current.growthMediaIds];for(const [index,item] of numbered.entries()){setNotice(`Bild ${index+1} von 9 wird hochgeladen …`);growthMediaIds[item.number-1]=await uploadFile(item.file)}await save({...current.current,growthMediaIds});setNotice("Alle neun Wachstumsbilder wurden gespeichert.")}catch(error){setNotice(error instanceof Error?error.message:"Sammelupload fehlgeschlagen.")}finally{setBusy(false)}}
  async function resetStage(stage:number){try{const growthMediaIds=[...appearance.growthMediaIds];growthMediaIds[stage]=null;await save({...appearance,growthMediaIds});setNotice(`Stufe ${stage} verwendet wieder die automatisch erzeugte SVG.`)}catch(error){setNotice(error instanceof Error?error.message:"Zurücksetzen fehlgeschlagen.")}}
  async function saveMessage(stage:number,message:string){if(busy)return;const trimmed=message.trim();if(!trimmed){setNotice(`Bitte gib für Stufe ${stage} einen Motivationsspruch ein.`);return}setBusy(true);try{const growthMessages=[...current.current.growthMessages];growthMessages[stage]=trimmed;await save({...current.current,growthMessages});setNotice(`Motivationsspruch für Stufe ${stage} wurde gespeichert.`)}catch(error){setNotice(error instanceof Error?error.message:"Der Motivationsspruch konnte nicht gespeichert werden.")}finally{setBusy(false)}}
  return <div className="appearance-panels"><article className="panel security-panel"><small>ERSCHEINUNGSBILD</small><h2>Frau mit Katze</h2><p>Lade optional eine freigestellte PNG- oder WebP-Grafik hoch. Empfohlen sind Hochformat, transparenter Hintergrund und maximal 5 MB.</p>{appearance.figureMediaId&&<div className="figure-preview"><img src={`/api/media/${appearance.figureMediaId}`} alt="Vorschau der hochgeladenen Figur"/></div>}<form className="admin-form" onSubmit={uploadFigure}><label>Neue Grafik<input name="file" type="file" accept="image/png,image/webp" required/></label><div className="form-row"><button className="primary">Hochladen</button>{appearance.figureMediaId&&<button type="button" onClick={()=>save({...appearance,figureMediaId:null}).then(()=>setNotice("Standardfigur wiederhergestellt."))}>Standard verwenden</button>}</div></form></article>
  <article className="panel growth-admin"><small>KRAFTBAUM</small><h2>Neun Wachstumsstufen</h2><p>Die App erzeugt alle Stufen automatisch als SVG. Eigene Bilder sind optional und ersetzen immer nur die jeweilige Stufe. Der Spruch erscheint direkt unter dem Baum.</p><label className={`stage-upload batch-upload ${busy?"disabled":""}`}>{busy?"Upload läuft …":"Alle Bilder 1–9 gemeinsam hochladen"}<input type="file" accept="image/png,image/webp" multiple disabled={busy} onChange={uploadAll}/></label><div className="growth-stage-grid">{labels.map((label,stage)=><section key={label}><div className="growth-stage-preview">{appearance.growthMediaIds[stage]?<img src={`/api/media/${appearance.growthMediaIds[stage]}`} alt={`Vorschau ${label}`}/>:<span>{stage===0?"●":"⌁"}</span>}</div><b>{stage}. {label}</b><label className={`stage-upload ${busy?"disabled":""}`}>{busy?"Bitte warten …":"Bild ersetzen"}<input type="file" accept="image/png,image/webp" disabled={busy} onChange={event=>{const file=event.target.files?.[0];event.target.value="";if(file)uploadStage(stage,file)}}/></label>{appearance.growthMediaIds[stage]&&<button type="button" disabled={busy} onClick={()=>resetStage(stage)}>SVG verwenden</button>}<form className="growth-message-form" onSubmit={event=>{event.preventDefault();const value=new FormData(event.currentTarget).get("message");if(typeof value==="string")saveMessage(stage,value)}}><label>Motivationsspruch<textarea name="message" defaultValue={appearance.growthMessages[stage]} maxLength={240} rows={3} required/></label><small>Maximal 240 Zeichen</small><button className="secondary" disabled={busy}>Spruch speichern</button></form></section>)}</div></article>{notice&&<p className="admin-notice" role="status" aria-live="polite">{notice}</p>}</div>;
}
