"use client";
/* eslint-disable @next/next/no-img-element */
import { FormEvent,useEffect,useState } from "react";

type Appearance={figureMediaId:string|null;growthMediaIds:Array<string|null>};
const empty:Appearance={figureMediaId:null,growthMediaIds:Array(9).fill(null)};
const labels=["Samen","Erster Trieb","Junge Pflanze","Zwei Äste","Vier Äste","Feine Zweige","Mehr Blätter","Blüten","Rote Äpfel"];

export function AdminAppearance(){
  const [appearance,setAppearance]=useState<Appearance>(empty),[notice,setNotice]=useState("");
  useEffect(()=>{fetch("/api/admin/settings/appearance").then(r=>r.json()).then(value=>setAppearance({figureMediaId:value.figureMediaId||null,growthMediaIds:Array.from({length:9},(_,i)=>value.growthMediaIds?.[i]||null)}))},[]);
  async function save(next:Appearance){const response=await fetch("/api/admin/settings/appearance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(next)}),result=await response.json();if(!response.ok)throw new Error(result.error||"Die Darstellung konnte nicht gespeichert werden.");setAppearance(next)}
  async function uploadFile(file:File){const upload=new FormData();upload.set("file",file);const response=await fetch("/api/admin/media",{method:"POST",body:upload}),result=await response.json();if(!response.ok)throw new Error(result.error||"Das Bild konnte nicht hochgeladen werden.");return result.id as string}
  async function uploadFigure(e:FormEvent<HTMLFormElement>){e.preventDefault();try{const file=new FormData(e.currentTarget).get("file");if(!(file instanceof File)||!file.size)return;const id=await uploadFile(file);await save({...appearance,figureMediaId:id});setNotice("Figur gespeichert. Sie erscheint ab sofort am Kraftbaum.")}catch(error){setNotice(error instanceof Error?error.message:"Upload fehlgeschlagen.")}}
  async function uploadStage(stage:number,file:File){try{const id=await uploadFile(file),growthMediaIds=[...appearance.growthMediaIds];growthMediaIds[stage]=id;await save({...appearance,growthMediaIds});setNotice(`Wachstumsstufe ${stage} wurde gespeichert.`)}catch(error){setNotice(error instanceof Error?error.message:"Upload fehlgeschlagen.")}}
  async function resetStage(stage:number){try{const growthMediaIds=[...appearance.growthMediaIds];growthMediaIds[stage]=null;await save({...appearance,growthMediaIds});setNotice(`Stufe ${stage} verwendet wieder die automatisch erzeugte SVG.`)}catch(error){setNotice(error instanceof Error?error.message:"Zurücksetzen fehlgeschlagen.")}}
  return <div className="appearance-panels"><article className="panel security-panel"><small>ERSCHEINUNGSBILD</small><h2>Frau mit Katze</h2><p>Lade optional eine freigestellte PNG- oder WebP-Grafik hoch. Empfohlen sind Hochformat, transparenter Hintergrund und maximal 5 MB.</p>{appearance.figureMediaId&&<div className="figure-preview"><img src={`/api/media/${appearance.figureMediaId}`} alt="Vorschau der hochgeladenen Figur"/></div>}<form className="admin-form" onSubmit={uploadFigure}><label>Neue Grafik<input name="file" type="file" accept="image/png,image/webp" required/></label><div className="form-row"><button className="primary">Hochladen</button>{appearance.figureMediaId&&<button type="button" onClick={()=>save({...appearance,figureMediaId:null}).then(()=>setNotice("Standardfigur wiederhergestellt."))}>Standard verwenden</button>}</div></form></article>
  <article className="panel growth-admin"><small>KRAFTBAUM</small><h2>Neun Wachstumsstufen</h2><p>Die App erzeugt alle Stufen automatisch als SVG. Eigene Bilder sind optional und ersetzen immer nur die jeweilige Stufe.</p><div className="growth-stage-grid">{labels.map((label,stage)=><section key={label}><div className="growth-stage-preview">{appearance.growthMediaIds[stage]?<img src={`/api/media/${appearance.growthMediaIds[stage]}`} alt=""/>:<span>{stage===0?"●":"⌁"}</span>}</div><b>{stage}. {label}</b><label className="stage-upload">Bild ersetzen<input type="file" accept="image/png,image/webp,image/svg+xml" onChange={event=>{const file=event.target.files?.[0];if(file)uploadStage(stage,file)}}/></label>{appearance.growthMediaIds[stage]&&<button type="button" onClick={()=>resetStage(stage)}>SVG verwenden</button>}</section>)}</div></article>{notice&&<p className="admin-notice" role="status">{notice}</p>}</div>;
}
