"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import {ChangeEvent,useCallback,useEffect,useRef,useState} from "react";
import {messageOf,requestJson} from "./client-api";
import {appTimeZone} from "@/lib/app-time";

type Backup={name:string;createdAt:string;kind:string;revision:string|null;restorable:boolean};
type ProcessStatus={status?:string;message?:string}|null;
type Health={checkedAt:string;revision:string;uptimeSeconds:number;database:string;disk:{freeBytes:number;freePercent:number};latestBackup:{createdAt:string;ageHours:number}|null;mailQueue:Record<string,number>;terminalFailed:number;updateStatus:ProcessStatus;backupStatus:ProcessStatus;restoreStatus:ProcessStatus;alerts:{level:"warning"|"error";code:string;message:string}[]};
type BackupData={backups:Backup[];backupStatus:ProcessStatus;restoreStatus:ProcessStatus};
type Validated={uploadId:string;manifest:{createdAt:string;kind:string;revision:string};totalBytes:number;message:string};

const bytes=(value:number)=>`${new Intl.NumberFormat("de-DE",{maximumFractionDigits:1}).format(value/1024/1024)} MB`;
const age=(hours:number)=>hours<1?`${Math.max(1,Math.round(hours*60))} Min.`:hours<24?`${new Intl.NumberFormat("de-DE",{maximumFractionDigits:1}).format(hours)} Std.`:`${new Intl.NumberFormat("de-DE",{maximumFractionDigits:1}).format(hours/24)} Tage`;
const duration=(seconds:number)=>seconds<3600?`${Math.floor(seconds/60)} Min.`:`${Math.floor(seconds/3600)} Std. ${Math.floor(seconds%3600/60)} Min.`;
const processLabel=(status:ProcessStatus)=>status?.status==="failed"?"Fehlgeschlagen":status?.status==="running"?"Läuft":status?.status==="success"?"Erfolgreich":"Keine Meldung";

export function AdminSystem(){
  const [health,setHealth]=useState<Health|null>(null),[backups,setBackups]=useState<BackupData>({backups:[],backupStatus:null,restoreStatus:null}),[notice,setNotice]=useState(""),[busy,setBusy]=useState(""),[loading,setLoading]=useState(false),[validated,setValidated]=useState<Validated|null>(null),[confirmation,setConfirmation]=useState(""),fileRef=useRef<HTMLInputElement>(null);
  const load=useCallback(async()=>{setLoading(true);try{const [h,b]=await Promise.all([requestJson<Health>("/api/admin/system"),requestJson<BackupData>("/api/admin/backups")]);setHealth(h);setBackups(b)}catch(error){setNotice(messageOf(error))}finally{setLoading(false)}},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void load()},10000),visible=()=>{if(document.visibilityState==="visible")void load()};document.addEventListener("visibilitychange",visible);window.addEventListener("focus",visible);return()=>{window.clearInterval(timer);document.removeEventListener("visibilitychange",visible);window.removeEventListener("focus",visible)}},[load]);
  async function createBackup(){setBusy("backup");try{const result=await requestJson<{message:string}>("/api/admin/backups",{method:"POST"});setNotice(result.message);window.setTimeout(load,2500)}catch(error){setNotice(messageOf(error))}finally{setBusy("")}}
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setBusy("upload");setValidated(null);try{const result=await requestJson<Validated>("/api/admin/backups/upload",{method:"POST",headers:{"content-type":"application/gzip"},body:file});setValidated(result);setNotice(result.message)}catch(error){setNotice(messageOf(error));event.target.value=""}finally{setBusy("")}}
  async function restore(){if(!validated)return;setBusy("restore");try{const result=await requestJson<{message:string}>("/api/admin/backups/upload",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({uploadId:validated.uploadId,confirmation})});setNotice(result.message);setValidated(null);setConfirmation("");if(fileRef.current)fileRef.current.value="";window.setTimeout(load,4000)}catch(error){setNotice(messageOf(error))}finally{setBusy("")}}
  return <div className="admin-section-stack system-admin">
    {notice&&<button className="admin-notice" onClick={()=>setNotice("")}>{notice} ×</button>}
    <article className="panel system-overview"><div className="panel-title"><div><small>SYSTEMÜBERWACHUNG</small><h2>Status & Warnungen</h2><p>Aktualisiert sich alle 10 Sekunden sowie beim Öffnen dieses Browser-Tabs.</p></div><button className="system-refresh" disabled={loading} onClick={load}>{loading?"Prüfung läuft …":"Jetzt prüfen"}</button></div>
      {health&&<><div className="system-metrics"><span><b className={health.database==="ok"?"good":"bad"}>{health.database==="ok"?"● In Ordnung":"● Fehler"}</b><small>Datenbank</small></span><span><b>{health.disk.freePercent} %</b><small>{bytes(health.disk.freeBytes)} frei</small></span><span><b>{health.latestBackup?age(health.latestBackup.ageHours):"–"}</b><small>Letztes Backup</small></span><span><b className={health.terminalFailed?"bad":"good"}>{health.terminalFailed}</b><small>Endgültig fehlgeschlagene Mails</small></span></div>
        <div className="system-details"><span><small>App läuft seit</small><b>{duration(health.uptimeSeconds)}</b></span><span><small>E-Mail-Warteschlange</small><b>{health.mailQueue.queued||0} offen · {health.mailQueue.sending||0} aktiv</b></span><span><small>Letztes Update</small><b>{processLabel(health.updateStatus)}</b></span><span><small>Backup / Restore</small><b>{processLabel(health.backupStatus)} / {processLabel(health.restoreStatus)}</b></span></div>
        <div className="health-alerts">{health.alerts.map(alert=><p className={alert.level} key={alert.code}><b>{alert.level==="error"?"Handlungsbedarf":"Hinweis"}</b> {alert.message}</p>)}{!health.alerts.length&&<p className="good"><b>Alles in Ordnung.</b> Keine Auffälligkeiten erkannt.</p>}</div><small className="system-checked">Zuletzt geprüft: {new Date(health.checkedAt).toLocaleString("de-DE",{timeZone:appTimeZone()})} · Revision {health.revision}</small></>}
    </article>
    <article className="panel"><div className="panel-title"><div><small>DATENSICHERUNG</small><h2>Backups</h2><p>Erstelle ein Server-Backup oder lade eine vorhandene Sicherung herunter.</p></div><button className="primary" disabled={Boolean(busy)} onClick={createBackup}>{busy==="backup"?"Wird erstellt …":"Backup jetzt erstellen"}</button></div>{backups.backupStatus&&<p className="form-feedback">Letzter Auftrag: {backups.backupStatus.status}{backups.backupStatus.message?` · ${backups.backupStatus.message}`:""}</p>}<div className="backup-list">{backups.backups.map(item=><div key={item.name}><span><b>{new Date(item.createdAt).toLocaleString("de-DE",{timeZone:appTimeZone()})}</b><small>{item.kind} · Revision {item.revision||"unbekannt"}{!item.restorable?" · altes Format, nur Download":""}</small></span><a href={`/api/admin/backups/${encodeURIComponent(item.name)}`} download>Herunterladen</a></div>)}{!backups.backups.length&&<p>Noch kein Backup gefunden.</p>}</div></article>
    <article className="panel restore-panel"><small>WIEDERHERSTELLUNG</small><h2>Backup einspielen</h2><p>Die Datei wird vorab auf sichere Pfade, Prüfsummen und Datenbankintegrität geprüft.</p><label className="backup-upload">Backup-Datei auswählen<input ref={fileRef} type="file" accept=".tar.gz,.tgz,application/gzip" onChange={upload}/></label>{busy==="upload"&&<p className="form-feedback">Upload und Validierung laufen …</p>}{validated&&<div className="restore-confirm"><p className="success"><b>Backup gültig.</b> {new Date(validated.manifest.createdAt).toLocaleString("de-DE",{timeZone:appTimeZone()})} · Revision {validated.manifest.revision?.slice(0,12)||"unbekannt"} · {bytes(validated.totalBytes)}</p><p className="danger-copy"><b>Achtung:</b> Die aktuellen Daten werden ersetzt. Zuvor erstellt der Server automatisch eine weitere Sicherung; anschließend startet die App kurz neu.</p><label>Zur Bestätigung <b>BACKUP WIEDERHERSTELLEN</b> eingeben<input value={confirmation} onChange={event=>setConfirmation(event.target.value)} autoComplete="off"/></label><button className="danger-action" disabled={busy==="restore"||confirmation!=="BACKUP WIEDERHERSTELLEN"} onClick={restore}>{busy==="restore"?"Wiederherstellung startet …":"Geprüftes Backup wiederherstellen"}</button></div>}{backups.restoreStatus&&<p className="form-feedback">Letzte Wiederherstellung: {backups.restoreStatus.status}{backups.restoreStatus.message?` · ${backups.restoreStatus.message}`:""}</p>}</article>
  </div>;
}
