"use client";
/* Live attendance is intentionally synchronized from the server while a check-in is open. */
/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-img-element */
import {useCallback,useEffect,useState} from "react";
import {AdminScanner} from "./admin-scanner";
type Session={id:string;sequence:number;title:string;startsAt:string};
type Person={id:string;firstName:string;lastName:string;email:string};
type Checkin={id:string;url:string;expiresAt:string;qrCode:string};
export function AdminAttendanceWorkspace({sessions,roster,onMark}:{sessions:Session[];roster:Person[];onMark:(userId:string,sessionId:string)=>Promise<void>}){
  const [sessionId,setSessionId]=useState(sessions[0]?.id||""),[attendees,setAttendees]=useState<Set<string>>(new Set()),[checkin,setCheckin]=useState<Checkin|null>(null),[notice,setNotice]=useState("");
  useEffect(()=>{if(!sessions.some(item=>item.id===sessionId))setSessionId(sessions[0]?.id||"")},[sessions,sessionId]);
  const load=useCallback(async()=>{if(!sessionId){setAttendees(new Set());return}const response=await fetch(`/api/admin/attendance?sessionId=${encodeURIComponent(sessionId)}`),result=await response.json();if(response.ok)setAttendees(new Set((result.attendees as {userId:string}[]).map(item=>item.userId)))},[sessionId]);
  useEffect(()=>{void load();if(!checkin)return;const timer=window.setInterval(load,4000);return()=>window.clearInterval(timer)},[load,checkin]);
  async function mark(userId:string){if(attendees.has(userId))return;await onMark(userId,sessionId);await load()}
  async function open(){if(!sessionId){setNotice("Bitte wähle zuerst einen Termin.");return}const response=await fetch("/api/admin/session-checkin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId,minutes:45})}),result=await response.json();if(!response.ok){setNotice(result.error);return}setCheckin(result);setNotice("Der gemeinsame Check-in ist 45 Minuten geöffnet.")}
  async function close(){if(!checkin)return;await fetch("/api/admin/session-checkin",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({checkinId:checkin.id})});setCheckin(null);setNotice("Der gemeinsame Check-in wurde geschlossen.")}
  const selected=sessions.find(item=>item.id===sessionId);
  return <div className="attendance-workspace"><section className="attendance-mode"><label>Termin<select value={sessionId} onChange={event=>{setSessionId(event.target.value);setCheckin(null)}}>{sessions.map(item=><option value={item.id} key={item.id}>{item.sequence}. {item.title}</option>)}</select></label><div className="attendance-live"><b>{attendees.size} von {roster.length}</b><span>anwesend · {selected&&new Date(selected.startsAt).toLocaleDateString("de-DE")}</span></div></section><div className="attendance-columns"><section className="friendly-roster"><p className="eyebrow">Persönlich begrüßen</p><h3>Teilnehmerliste</h3><p>Beim Ankommen einmal auf den Namen tippen.</p>{roster.map(person=><button className={attendees.has(person.id)?"present":""} disabled={attendees.has(person.id)} onClick={()=>mark(person.id)} key={person.id}><span>{person.firstName[0]}{person.lastName[0]}</span><b>{person.firstName} {person.lastName}</b><i>{attendees.has(person.id)?"Anwesend ✓":"Als anwesend markieren"}</i></button>)}</section><section className="group-checkin"><p className="eyebrow">Für größere Gruppen</p><h3>Gemeinsamer Termin-QR</h3><p>Teilnehmerinnen scannen diesen QR selbst. Er gilt nur für den gewählten Termin und läuft nach 45 Minuten ab.</p>{checkin?<><img src={checkin.qrCode} alt="Gemeinsamer QR-Code für den Selbst-Check-in"/><small>Geöffnet bis {new Date(checkin.expiresAt).toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})} Uhr</small><button className="danger-action" onClick={close}>Check-in schließen</button></>:<button className="primary" onClick={open}>Gemeinsamen QR öffnen</button>}</section></div><details className="personal-scan"><summary>Persönlichen QR-Code scannen</summary><AdminScanner sessions={sessions} onSaved={load}/></details>{notice&&<p className="admin-notice" role="status">{notice}</p>}</div>
}
