"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AdminTwoFactor } from "./admin-two-factor";
import { AdminUsers } from "./admin-users";

type Course={id:string;title:string;description:string;sessionCount:number;durationMinutes:number;startsAt:string|null;endsAt:string|null;location:string|null;navigationUrl:string|null;status:string;treeVariant:string};
type User={id:string;email:string;role:string;firstName:string;lastName:string;status:string;courseCount:number};
type Session={id:string;sequence:number;title:string;startsAt:string;endsAt:string;location:string|null};
type Roster={id:string;firstName:string;lastName:string;email:string;attendedCount:number;completedAt:string|null};
type ContentItem={id:string;title:string;kind:string;status:string;ruleType:string;content_updated_at:string};
type Tab="overview"|"courses"|"codes"|"attendance"|"content"|"users"|"security";

async function api(url:string,options?:RequestInit){const response=await fetch(url,options);const result=await response.json().catch(()=>({error:"Unbekannter Fehler"}));if(!response.ok)throw new Error(result.error||"Anfrage fehlgeschlagen");return result;}
const json=(body:unknown)=>({method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});

export function AdminConsole({close,requireSecurity=false}:{close:()=>void;requireSecurity?:boolean}){
  const [tab,setTab]=useState<Tab>(requireSecurity?"security":"overview"),[courses,setCourses]=useState<Course[]>([]),[users,setUsers]=useState<User[]>([]),[selected,setSelected]=useState(""),[sessions,setSessions]=useState<Session[]>([]),[roster,setRoster]=useState<Roster[]>([]),[contents,setContents]=useState<ContentItem[]>([]),[codes,setCodes]=useState<{code:string;assignedEmail:string|null}[]>([]),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{try{const [c,u]=await Promise.all([api("/api/admin/courses"),api("/api/admin/users")]);setCourses(c.courses);setUsers(u.users);if(!selected&&c.courses[0])setSelected(c.courses[0].id);}catch(e){setNotice((e as Error).message)}},[selected]);
  // Data arrives asynchronously; these effects synchronize the selected server records.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{load()},[load]);
  useEffect(()=>{if(!selected)return;Promise.all([api(`/api/admin/courses/${selected}/sessions`),api(`/api/admin/courses/${selected}/roster`),api(`/api/admin/content?courseId=${selected}`)]).then(([s,r,c])=>{setSessions(s.sessions);setRoster(r.roster);setContents(c.items)}).catch(e=>setNotice(e.message));},[selected]);
  async function submitCourse(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/admin/courses",json({title:f.get("title"),description:f.get("description"),sessionCount:Number(f.get("sessionCount")),durationMinutes:Number(f.get("durationMinutes")),location:f.get("location"),navigationUrl:f.get("navigationUrl"),status:"published"}));e.currentTarget.reset();setNotice("Kurs wurde angelegt.");await load()}catch(err){setNotice((err as Error).message)}}
  async function submitSession(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/api/admin/courses/${selected}/sessions`,json({sequence:Number(f.get("sequence")),title:f.get("title"),startsAt:new Date(String(f.get("startsAt"))).toISOString(),endsAt:new Date(String(f.get("endsAt"))).toISOString(),location:f.get("location")||undefined,navigationUrl:f.get("navigationUrl")||undefined}));e.currentTarget.reset();setNotice("Termin wurde angelegt.");const result=await api(`/api/admin/courses/${selected}/sessions`);setSessions(result.sessions)}catch(err){setNotice((err as Error).message)}}
  async function submitCodes(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const emails=String(f.get("emails")||"").split(/[\n,;]/).map(x=>x.trim()).filter(Boolean);const result=await api("/api/admin/codes",json({courseId:selected,type:f.get("type"),count:Number(f.get("count")),assignedEmails:emails}));setCodes(result.codes);setNotice(`${result.codes.length} Codes wurden erzeugt. Nur jetzt vollständig sichtbar.`)}catch(err){setNotice((err as Error).message)}}
  async function mark(userId:string,sessionId:string){try{await api("/api/admin/attendance",json({userId,sessionId,source:"list"}));setNotice("Anwesenheit gespeichert.");const r=await api(`/api/admin/courses/${selected}/roster`);setRoster(r.roster)}catch(err){setNotice((err as Error).message)}}
  async function submitContent(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),kind=String(f.get("kind"));try{let assetPath:undefined|string;const file=f.get("file");if(file instanceof File&&file.size){const upload=new FormData();upload.set("file",file);const saved=await api("/api/admin/media",{method:"POST",body:upload});assetPath=saved.id}await api("/api/admin/content",json({courseId:selected,title:f.get("title"),kind,body:String(f.get("body")||"")||undefined,externalUrl:String(f.get("externalUrl")||"")||undefined,assetPath,status:f.get("status"),ruleType:f.get("ruleType"),threshold:Number(f.get("threshold"))||undefined,sessionSequence:Number(f.get("sessionSequence"))||undefined}));form.reset();setNotice("Inhalt wurde gespeichert.");const result=await api(`/api/admin/content?courseId=${selected}`);setContents(result.items)}catch(err){setNotice((err as Error).message)}}
  const selectedCourse=courses.find(c=>c.id===selected);
  return <main className="admin-page real-admin"><aside><button className="brand admin-brand" onClick={close}><span className="brand-mark">a</span><span><b>ANJA</b><small>ADMIN</small></span></button><nav>{([['overview','Übersicht'],['courses','Kurse & Termine'],['codes','Codes'],['attendance','Anwesenheit'],['content','Inhalte'],['users','Teilnehmer'],['security','Sicherheit']] as [Tab,string][]).map(([id,label])=><button className={tab===id?"selected":""} onClick={()=>setTab(id)} key={id}>{label}<span>›</span></button>)}</nav><button className="back" onClick={close}>← Teilnehmeransicht</button></aside><section className="admin-main"><header><div><p className="eyebrow">Administration</p><h1>{tab==="overview"?"Guten Abend, Anja.":tab==="courses"?"Kurse & Termine":tab==="codes"?"Zugangscodes":tab==="attendance"?"Anwesenheit":tab==="content"?"Kursinhalte":tab==="security"?"Sicherheit":"Teilnehmer"}</h1></div><button className="admin-avatar">A</button></header>{notice&&<button className="admin-notice" onClick={()=>setNotice("")}>{notice} ×</button>}
  {tab==="overview"&&<><div className="metric-grid"><article><span>AKTIVE TEILNEHMER</span><b>{users.filter(u=>u.role==="user"&&u.status==="active").length}</b><small>registrierte Konten</small></article><article><span>KURSE</span><b>{courses.length}</b><small>{courses.filter(c=>c.status==="published").length} veröffentlicht</small></article><article><span>TERMINE</span><b>{sessions.length}</b><small>im gewählten Kurs</small></article><article><span>APP-STATUS</span><b className="healthy">● Aktuell</b><small>Revision 0.7.0</small></article></div><article className="panel"><div className="panel-title"><div><small>AKTUELLE KURSE</small><h2>Deine Kursdurchläufe</h2></div><button className="primary" onClick={()=>setTab("courses")}>Kurs anlegen</button></div><div className="admin-list">{courses.length?courses.map(c=><button onClick={()=>{setSelected(c.id);setTab("courses")}} key={c.id}><div><b>{c.title}</b><small>{c.sessionCount} × {c.durationMinutes} Minuten · {c.location||"Ort offen"}</small></div><span>{c.status} ›</span></button>):<p>Noch kein Kurs angelegt.</p>}</div></article></>}
  {tab==="courses"&&<div className="admin-workspace"><article className="panel"><small>NEUER KURSDURCHLAUF</small><form className="admin-form" onSubmit={submitCourse}><label>Titel<input name="title" required placeholder="Beginner Herbst 2026"/></label><label>Beschreibung<textarea name="description"/></label><div className="form-row"><label>Einheiten<input name="sessionCount" type="number" min="1" defaultValue="8" required/></label><label>Minuten je Einheit<input name="durationMinutes" type="number" min="15" defaultValue="90" required/></label></div><label>Ort<input name="location" placeholder="Studio Anja tanzt · Herrieden"/></label><label>Navigationslink<input name="navigationUrl" type="url" placeholder="https://…"/></label><button className="primary">Kurs anlegen</button></form></article><article className="panel"><small>TERMINE VERWALTEN</small><select className="admin-select" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Kurs wählen</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select>{selected&&<><form className="admin-form compact" onSubmit={submitSession}><div className="form-row"><label>Nr.<input name="sequence" type="number" min="1" required/></label><label>Titel<input name="title" required/></label></div><div className="form-row"><label>Beginn<input name="startsAt" type="datetime-local" required/></label><label>Ende<input name="endsAt" type="datetime-local" required/></label></div><label>Ort<input name="location" defaultValue={selectedCourse?.location||""}/></label><label>Navigationslink<input name="navigationUrl" type="url" defaultValue={selectedCourse?.navigationUrl||""}/></label><button className="primary">Termin hinzufügen</button></form><div className="admin-list">{sessions.map(s=><div className="list-row" key={s.id}><b>{s.sequence}. {s.title}</b><small>{new Date(s.startsAt).toLocaleString("de-DE")}</small></div>)}</div></>}</article></div>}
  {tab==="codes"&&<div className="admin-workspace"><article className="panel"><small>CODEPAKET ERZEUGEN</small><form className="admin-form" onSubmit={submitCodes}><label>Kurs<select name="courseId" value={selected} onChange={e=>setSelected(e.target.value)} required><option value="">Kurs wählen</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Codetyp<select name="type"><option value="attendance">Präsenzkurs · gestaffelt</option><option value="full">Vollzugang</option><option value="event">Event</option></select></label><label>Anzahl<input name="count" type="number" min="1" max="500" defaultValue="8" required/></label><label>E-Mail-Zuordnung <small>optional, eine Adresse pro Zeile</small><textarea name="emails" placeholder="anna@example.de"/></label><button className="primary">Codes sicher erzeugen</button></form></article><article className="panel code-results"><small>EINMALIGE AUSGABE</small>{codes.length?codes.map(c=><div key={c.code}><code>{c.code}</code><span>{c.assignedEmail||"frei"}</span><button onClick={()=>navigator.clipboard.writeText(c.code)}>Kopieren</button></div>):<p>Neu erzeugte Codes werden hier einmalig angezeigt.</p>}</article></div>}
  {tab==="attendance"&&<article className="panel"><div className="panel-title"><div><small>ANWESENHEIT</small><h2>{selectedCourse?.title||"Kurs wählen"}</h2></div><select className="admin-select inline" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Kurs wählen</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></div><div className="attendance-grid">{sessions.map(s=><section key={s.id}><h3>{s.sequence}. {s.title}</h3><small>{new Date(s.startsAt).toLocaleDateString("de-DE")}</small>{roster.map(p=><button onClick={()=>mark(p.id,s.id)} key={p.id}><span>{p.firstName[0]}{p.lastName[0]}</span><b>{p.firstName} {p.lastName}</b><i>Anwesend ✓</i></button>)}</section>)}</div>{!sessions.length&&<p>Lege zunächst Termine für diesen Kurs an.</p>}</article>}
  {tab==="content"&&<div className="admin-workspace"><article className="panel"><small>INHALT ANLEGEN</small><form className="admin-form" onSubmit={submitContent}><label>Kurs<select value={selected} onChange={e=>setSelected(e.target.value)} required><option value="">Kurs wählen</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label>Titel<input name="title" required/></label><div className="form-row"><label>Art<select name="kind"><option value="text">Text</option><option value="image">Bild</option><option value="pdf">PDF</option><option value="video">Eigenes Video</option><option value="youtube">YouTube</option><option value="vimeo">Vimeo</option><option value="link">Link</option></select></label><label>Status<select name="status"><option value="published">Veröffentlicht</option><option value="draft">Entwurf</option></select></label></div><label>Text / Beschreibung<textarea name="body"/></label><label>Externer Link<input name="externalUrl" type="url" placeholder="https://…"/></label><label>Datei <small>Bilder 5 MB · PDF 20 MB · Video 5 GB</small><input name="file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf,video/mp4,video/webm"/></label><label>Freischaltung<select name="ruleType"><option value="immediate">Sofort</option><option value="attendance_count">Nach Anzahl Teilnahmen</option><option value="session">Nach bestimmter Einheit</option><option value="completion">Nach Kursabschluss</option><option value="manual">Nur manuell</option></select></label><div className="form-row"><label>Anzahl Teilnahmen<input name="threshold" type="number" min="1"/></label><label>Einheit Nr.<input name="sessionSequence" type="number" min="1"/></label></div><button className="primary">Inhalt speichern</button></form></article><article className="panel"><small>INHALTE IM KURS</small><div className="admin-list">{contents.map(item=><div className="list-row" key={item.id}><div><b>{item.title}</b><small>{item.kind} · {item.ruleType} · Stand {new Date(item.content_updated_at).toLocaleString("de-DE")}</small></div><span>{item.status}</span></div>)}{!contents.length&&<p>Noch keine Inhalte angelegt.</p>}</div></article></div>}
  {tab==="users"&&<AdminUsers users={users} reload={load} notify={setNotice}/>}
  {tab==="security"&&<AdminTwoFactor/>}
  </section></main>;
}
