"use client";
/* Initial admin data is loaded from protected endpoints after mounting. */
/* eslint-disable react-hooks/set-state-in-effect */
import {FormEvent,useCallback,useEffect,useState} from "react";
type Course={id:string;title:string;status:string};
type Message={id:string;audience:"all"|"course";courseId:string|null;courseTitle:string|null;title:string;body:string;url:string|null;recipientCount:number;deliveredCount:number;failedCount:number;createdAt:string;createdBy:string|null};
async function json(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"content-type":"application/json",...options?.headers}}),result=await response.json().catch(()=>({error:"Der Server hat keine lesbare Antwort geliefert."}));if(!response.ok)throw new Error(result.error||"Die Aktion konnte nicht abgeschlossen werden.");return result}
export function AdminPush(){
  const [settings,setSettings]=useState<{configured?:boolean;publicKey?:string;subject?:string}>({}),[courses,setCourses]=useState<Course[]>([]),[messages,setMessages]=useState<Message[]>([]),[audience,setAudience]=useState<"all"|"course">("course"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const [configuration,courseResult,messageResult]=await Promise.all([json("/api/admin/settings/push"),json("/api/admin/courses"),json("/api/admin/push-messages")]);setSettings(configuration);setCourses(courseResult.courses||[]);setMessages(messageResult.messages||[])}catch(error){setNotice((error as Error).message)}},[]);
  useEffect(()=>{void load()},[load]);
  async function configure(e:FormEvent<HTMLFormElement>){e.preventDefault();const subject=new FormData(e.currentTarget).get("subject");setBusy(true);try{const result=await json("/api/admin/settings/push",{method:"POST",body:JSON.stringify({subject})});setSettings({configured:true,publicKey:result.publicKey,subject:String(subject)});setNotice("Push-Schlüssel wurden erzeugt und verschlüsselt gespeichert.")}catch(error){setNotice((error as Error).message)}finally{setBusy(false)}}
  async function test(){setBusy(true);setNotice("Testnachricht wird versendet …");try{const result=await json("/api/admin/settings/push/test",{method:"POST"});setNotice(`${result.message} Falls sie nicht erscheint, prüfe unter iOS „Einstellungen → Mitteilungen → Stärke deine Mitte“ sowie einen aktiven Fokusmodus.`)}catch(error){setNotice(`Push-Test fehlgeschlagen: ${(error as Error).message}`)}finally{setBusy(false)}}
  async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setBusy(true);setNotice("Push-Nachricht wird versendet …");try{const result=await json("/api/admin/push-messages",{method:"POST",body:JSON.stringify({audience,courseId:audience==="course"?data.get("courseId"):null,title:data.get("title"),body:data.get("body"),url:data.get("url")||"/"})});setNotice(result.recipientCount?`${result.message} ${result.deliveredCount} Geräte nahmen die Nachricht an${result.failedCount?`, bei ${result.failedCount} Geräten schlug die Zustellung fehl`:""}.`:"Die Nachricht wurde gespeichert, aber in dieser Empfängergruppe hat noch niemand Push aktiviert.");form.reset();setAudience("course");await load()}catch(error){setNotice(`Push konnte nicht versendet werden: ${(error as Error).message}`)}finally{setBusy(false)}}
  return <div className="admin-section-stack"><article className="panel security-panel"><small>BENACHRICHTIGUNGEN</small><h2>Web Push</h2><p>Web Push läuft direkt über Browser und Betriebssystem. Es ist kein Firebase-Konto nötig. Push-Nachrichten enthalten keine Gesundheits- oder Kontaktdaten.</p>{settings.configured?<div className="security-ok"><b>✓ Web Push ist eingerichtet</b><p>Kontakt: {settings.subject}</p><button type="button" onClick={test} disabled={busy}>{busy?"Test läuft …":"Test-Push an mein Administrationskonto"}</button><small>Der Test erreicht alle Geräte, auf denen du Push mit diesem Administrationskonto aktiviert hast.</small></div>:<form className="admin-form" onSubmit={configure}><label>Technischer Kontakt <small>z. B. mailto:kontakt@example.de</small><input name="subject" required placeholder="mailto:kontakt@example.de"/></label><button className="primary" disabled={busy}>Push sicher einrichten</button></form>}</article>
  {settings.configured&&<article className="panel push-composer"><small>MANUELLER VERSAND</small><h2>Nachricht senden</h2><p>Erreicht werden nur aktive Teilnehmerinnen, die Push auf mindestens einem Gerät freiwillig aktiviert haben.</p><form className="admin-form" onSubmit={send}><fieldset><legend>Empfängerinnen</legend><label className="check"><input type="radio" name="audience" checked={audience==="course"} onChange={()=>setAudience("course")}/><span>Teilnehmerinnen eines Kurses</span></label><label className="check"><input type="radio" name="audience" checked={audience==="all"} onChange={()=>setAudience("all")}/><span>Alle Teilnehmerinnen mit aktivem Push</span></label></fieldset>{audience==="course"&&<label>Kurs<select name="courseId" required defaultValue=""><option value="">Kurs auswählen</option>{courses.map(course=><option value={course.id} key={course.id}>{course.title}{course.status==="archived"?" · archiviert":""}</option>)}</select></label>}<label>Titel <small>maximal 80 Zeichen</small><input name="title" minLength={2} maxLength={80} required placeholder="Eine kleine Erinnerung für dich"/></label><label>Nachricht <small>maximal 240 Zeichen, keine sensiblen Angaben</small><textarea name="body" minLength={2} maxLength={240} required placeholder="Wir freuen uns auf unsere gemeinsame Zeit."/></label><label>Ziel innerhalb der App<select name="url" defaultValue="/"><option value="/">Mein Baum · Startseite</option><option value="/?view=kurse">Kurse & freigeschaltete Inhalte</option><option value="/?view=termine">Termine & Veranstaltungen</option><option value="/?view=nuetzliches">Nützliches & Kontakt</option><option value="/?view=profil">Profil & Einstellungen</option></select></label><button className="primary" disabled={busy}>{busy?"Wird versendet …":"Push-Nachricht jetzt senden"}</button></form></article>}
  <article className="panel push-history"><small>VERSANDHISTORIE</small><h2>Gesendete Nachrichten</h2><p>Diese Historie dokumentiert den manuellen Versand dauerhaft und kann nicht verändert oder gelöscht werden.</p>{messages.length?<div>{messages.map(message=><article key={message.id}><header><div><b>{message.title}</b><span>{new Date(message.createdAt).toLocaleString("de-DE")} · {message.audience==="all"?"Alle Teilnehmerinnen":message.courseTitle||"Gelöschter Kurs"}</span></div></header><p>{message.body}</p><small>{message.recipientCount} Empfängerinnen · {message.deliveredCount} Geräte angenommen{message.failedCount?` · ${message.failedCount} fehlgeschlagen`:""}</small></article>)}</div>:<p>Noch keine manuelle Push-Nachricht versendet.</p>}</article>{notice&&<button type="button" className="admin-notice push-notice" onClick={()=>setNotice("")}>{notice} ×</button>}</div>;
}
