"use client";
import {useEffect,useRef,useState} from "react";
type Session={id:string;sequence:number;title:string};
type Detector={detect:(source:HTMLVideoElement)=>Promise<{rawValue:string}[]>};
type DetectorConstructor=new(options:{formats:string[]})=>Detector;
export function AdminScanner({sessions,onSaved}:{sessions:Session[];onSaved:()=>void}){
  const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<number|null>(null),[sessionId,setSessionId]=useState(""),[token,setToken]=useState(""),[active,setActive]=useState(false),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false);
  useEffect(()=>()=>stop(),[]);
  function stop(){if(timer.current)window.clearInterval(timer.current);stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;setActive(false)}
  async function start(){if(!sessionId){setNotice("Bitte zuerst einen Termin wählen.");return}try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});if(video.current){video.current.srcObject=stream.current;await video.current.play()}setActive(true);const BarcodeDetector=(window as unknown as {BarcodeDetector?:DetectorConstructor}).BarcodeDetector;if(!BarcodeDetector){setNotice("Dieses Gerät unterstützt die automatische Erkennung nicht. Nutze die manuelle Eingabe.");return}const detector=new BarcodeDetector({formats:["qr_code"]});timer.current=window.setInterval(async()=>{if(!video.current)return;const found=await detector.detect(video.current).catch(()=>[]);if(found[0]?.rawValue){setToken(found[0].rawValue);stop();await save(found[0].rawValue)}},500)}catch{setNotice("Die Kamera konnte nicht geöffnet werden. Prüfe die Browserfreigabe oder nutze die manuelle Eingabe.")}}
  async function save(value=token){if(!sessionId){setNotice("Bitte zuerst den Kurstermin auswählen.");return}if(!value.trim()){setNotice("Bitte den vollständigen QR-Code beziehungsweise Token eingeben.");return}setSaving(true);try{const response=await fetch("/api/admin/attendance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({qrToken:value.trim(),sessionId,source:"scan"})}),result=await response.json();if(!response.ok){setNotice(result.error);return}setToken("");setNotice("Anwesenheit per QR-Code gespeichert.");onSaved()}catch{setNotice("Die Anwesenheit konnte nicht gespeichert werden. Prüfe die Verbindung und versuche es erneut.")}finally{setSaving(false)}}
  return <section className="scanner-panel"><h3>QR-Code scannen</h3><label className="scanner-session">Kurstermin<select value={sessionId} onChange={event=>setSessionId(event.target.value)}><option value="">Termin wählen</option>{sessions.map(session=><option value={session.id} key={session.id}>{session.sequence}. {session.title}</option>)}</select></label><video ref={video} playsInline muted className={active?"scanner-video":"scanner-video hidden"}/><div><button type="button" className="primary" onClick={active?stop:start}>{active?"Kamera stoppen":"Kamera öffnen"}</button></div><details className="manual-scan"><summary>QR-Inhalt manuell eingeben</summary><div className="manual-scan-form"><label>QR-Code oder Token<textarea value={token} onChange={event=>setToken(event.target.value)} placeholder="Vollständigen Code aus einem externen Scanner hier einfügen" autoCapitalize="off" autoCorrect="off" spellCheck={false}/><small>Füge hier den vollständigen Inhalt des Teilnehmer-QR-Codes ein.</small></label><button type="button" className="primary manual-save" disabled={saving||!sessionId||!token.trim()} onClick={()=>save()}>{saving?"Wird gespeichert …":"Anwesenheit speichern"}</button></div></details>{notice&&<p className="scanner-notice" role="status">{notice}</p>}</section>
}
