"use client";
/* Initial protected inbox data is loaded after the authenticated client mounts. */
/* eslint-disable react-hooks/set-state-in-effect */
/* The authenticated avatar endpoint is intentionally loaded directly. */
/* eslint-disable @next/next/no-img-element */
import {useCallback,useEffect,useRef,useState} from "react";
import {appTimeZone} from "@/lib/app-time";
type Notification={id:string;title:string;body:string;url:string;readAt:string|null;createdAt:string};
type Props={profileImage?:boolean;avatarRevision?:number;initials:string;onProfile:()=>void;profileLabel:string};
export function NotificationInbox({profileImage,avatarRevision=0,initials,onProfile,profileLabel}:Props){
  const [items,setItems]=useState<Notification[]>([]),[unread,setUnread]=useState(0),[open,setOpen]=useState(false),[notice,setNotice]=useState("");const box=useRef<HTMLDivElement>(null);
  const load=useCallback(async()=>{try{const response=await fetch("/api/me/notifications",{cache:"no-store"}),data=await response.json();if(response.ok){setItems(data.notifications||[]);setUnread(data.unread||0)}}catch{/* Beim nächsten Öffnen erneut laden. */}},[]);
  useEffect(()=>{void load();const focus=()=>void load(),message=(event:MessageEvent)=>{if(event.data?.type==="NOTIFICATION_RECEIVED")void load()},outside=(event:PointerEvent)=>{if(!box.current?.contains(event.target as Node))setOpen(false)};window.addEventListener("focus",focus);navigator.serviceWorker?.addEventListener("message",message);document.addEventListener("pointerdown",outside);return()=>{window.removeEventListener("focus",focus);navigator.serviceWorker?.removeEventListener("message",message);document.removeEventListener("pointerdown",outside)}},[load]);
  async function toggle(){const next=!open;setOpen(next);if(!next)return;await load();if(unread){setUnread(0);setItems(current=>current.map(item=>({...item,readAt:item.readAt||new Date().toISOString()})));await fetch("/api/me/notifications",{method:"PATCH"})}}
  async function clear(){if(!items.length)return;const response=await fetch("/api/me/notifications",{method:"DELETE"});if(response.ok){setItems([]);setUnread(0);setNotice("Benachrichtigungen geleert.")}else setNotice("Benachrichtigungen konnten nicht geleert werden.")}
  return <div className="notification-inbox" ref={box}><button type="button" className="notification-avatar" onClick={toggle} aria-label={`Profil und Benachrichtigungen öffnen${unread?`, ${unread} ungelesen`:""}`} aria-expanded={open}>{profileImage?<img src={`/api/me/avatar?v=${avatarRevision}`} alt=""/>:<span>{initials}</span>}{unread>0&&<b aria-label={`${unread} ungelesene Benachrichtigungen`}>{unread>99?"99+":unread}</b>}</button>{open&&<section className="notification-popover"><header><div><small>DEINE NACHRICHTEN</small><h2>Benachrichtigungen</h2></div><button type="button" className="notification-clear" onClick={clear} disabled={!items.length} aria-label="Alle Benachrichtigungen leeren" title="Alle Benachrichtigungen leeren">🧹</button></header>{notice&&<p className="notification-notice" role="status">{notice}</p>}<div className="notification-list">{items.map(item=><button type="button" key={item.id} className={item.readAt?"":"unread"} onClick={()=>window.location.assign(item.url)}><span><b>{item.title}</b><time>{new Date(item.createdAt).toLocaleString("de-DE",{timeZone:appTimeZone(),dateStyle:"short",timeStyle:"short"})}</time></span><p>{item.body}</p></button>)}{!items.length&&<p className="notification-empty">Hier erscheinen deine letzten Nachrichten.</p>}</div><button type="button" className="notification-profile-action" onClick={()=>{setOpen(false);onProfile()}}>{profileLabel}<span aria-hidden="true">→</span></button></section>}</div>;
}
