"use client";
/* Authenticated profile images intentionally bypass the public image optimizer. */
/* eslint-disable @next/next/no-img-element */
import { ChangeEvent,FormEvent,useEffect,useRef,useState } from "react";
import { PushPreference } from "./push-preference";
import { messageOf,requestJson } from "./client-api";
type Profile={firstName:string;lastName:string;email:string;birthday:string|null;phone:string|null;emailVerifiedAt?:string|null;profileImage?:boolean};
type Section="email"|"password"|"privacy"|null;

export function ProfileSettings({onLogout,onProfileImageChange}:{onLogout:()=>void;onProfileImageChange:(present:boolean)=>void}){
  const [profile,setProfile]=useState<Profile|null>(null),[section,setSection]=useState<Section>(null),[notice,setNotice]=useState("Profil wird geladen …"),[busy,setBusy]=useState(false),[savingProfile,setSavingProfile]=useState(false),[avatarRevision,setAvatarRevision]=useState(0),[avatarPreview,setAvatarPreview]=useState<string|null>(null);
  const saveTimer=useRef<number|null>(null),previewUrl=useRef<string|null>(null);
  useEffect(()=>{requestJson<{profile:Profile}>("/api/me/profile").then(x=>{setProfile(x.profile);setNotice("")}).catch(e=>setNotice(messageOf(e)));return()=>{if(saveTimer.current)window.clearTimeout(saveTimer.current);if(previewUrl.current)URL.revokeObjectURL(previewUrl.current)}},[]);
  function open(next:Exclude<Section,null>){setSection(section===next?null:next);setNotice("")}
  async function request(body:Record<string,unknown>){setBusy(true);try{return await requestJson<{loggedOut?:boolean;profile?:Profile;email?:string;verificationRequired?:boolean}>("/api/me/profile",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)})}catch(e){setNotice(messageOf(e));return null}finally{setBusy(false)}}
  function scheduleProfile(form:HTMLFormElement){const f=new FormData(form),body={action:"profile",firstName:String(f.get("firstName")||"").trim(),lastName:String(f.get("lastName")||"").trim(),birthday:f.get("birthday")||null,phone:f.get("phone")||null};if(!body.firstName||!body.lastName){setNotice("Vorname und Nachname dürfen nicht leer sein.");return}if(saveTimer.current)window.clearTimeout(saveTimer.current);setSavingProfile(true);setNotice("Änderungen werden gespeichert …");saveTimer.current=window.setTimeout(async()=>{try{const result=await requestJson<{profile:Profile}>("/api/me/profile",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});setProfile(current=>current?{...current,...result.profile}:result.profile);setNotice("Alle Änderungen gespeichert.")}catch(e){setNotice(messageOf(e))}finally{setSavingProfile(false)}},650)}
  async function changeEmail(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),result=await request({action:"email",email:f.get("email"),currentPassword:f.get("currentPassword")});if(!result)return;setProfile(current=>current?{...current,email:result.email||current.email,emailVerifiedAt:result.verificationRequired?null:current.emailVerifiedAt}:current);if(result.verificationRequired)try{await requestJson("/api/me/verify-email",{method:"POST"});setNotice("Deine E-Mail-Adresse wurde geändert. Ein Bestätigungslink wurde an die neue Adresse gesendet.")}catch(e){setNotice(`Die E-Mail-Adresse wurde geändert, aber der Bestätigungslink konnte nicht gesendet werden: ${messageOf(e)} Du kannst ihn unten erneut anfordern.`)}else setNotice("Diese E-Mail-Adresse ist bereits hinterlegt.");form.reset()}
  async function changePassword(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),next=String(f.get("newPassword")||""),confirmation=String(f.get("confirmation")||"");if(next!==confirmation){setNotice("Die beiden neuen Passwörter stimmen nicht überein.");return}const result=await request({action:"password",currentPassword:f.get("currentPassword"),newPassword:next});if(result?.loggedOut){setNotice("Dein Passwort wurde geändert. Bitte melde dich mit dem neuen Passwort wieder an.");onLogout()}}
  async function anonymize(e:FormEvent<HTMLFormElement>){e.preventDefault();const result=await request({...Object.fromEntries(new FormData(e.currentTarget).entries()),action:"anonymize"});if(result?.loggedOut)onLogout()}
  async function verifyEmail(){setBusy(true);setNotice("Bestätigungsmail wird versendet …");try{await requestJson("/api/me/verify-email",{method:"POST"});setNotice("Bestätigungslink wurde versendet. Prüfe bitte auch den Spam-Ordner.")}catch(e){setNotice(`${messageOf(e)} Falls SMTP noch fehlt, richte es als Admin zuerst unter „E-Mail“ ein.`)}finally{setBusy(false)}}
  async function selectAvatar(e:ChangeEvent<HTMLInputElement>){const file=e.currentTarget.files?.[0];if(!file)return;if(previewUrl.current)URL.revokeObjectURL(previewUrl.current);previewUrl.current=URL.createObjectURL(file);setAvatarPreview(previewUrl.current);const data=new FormData();data.set("file",file);setBusy(true);setNotice("Profilbild wird hochgeladen …");try{await requestJson("/api/me/avatar",{method:"POST",body:data});setProfile(current=>current?{...current,profileImage:true}:current);setAvatarRevision(Date.now());onProfileImageChange(true);setNotice("Dein Profilbild wurde gespeichert.")}catch(error){setAvatarPreview(null);setNotice(messageOf(error))}finally{setBusy(false);e.currentTarget.value=""}}
  async function deleteAvatar(){if(!window.confirm("Möchtest du dein Profilbild wirklich löschen?"))return;setBusy(true);try{await requestJson("/api/me/avatar",{method:"DELETE"});if(previewUrl.current){URL.revokeObjectURL(previewUrl.current);previewUrl.current=null}setAvatarPreview(null);setProfile(current=>current?{...current,profileImage:false}:current);onProfileImageChange(false);setNotice("Dein Profilbild wurde gelöscht.")}catch(e){setNotice(messageOf(e))}finally{setBusy(false)}}
  if(!profile)return <p className="profile-notice" role="status">{notice}</p>;
  const avatarSource=avatarPreview||profile.profileImage?avatarPreview||`/api/me/avatar?v=${avatarRevision}`:null;
  return <div className="profile-settings compact-profile">
    <section className="avatar-editor"><div className="avatar-preview">{avatarSource?<img src={avatarSource} alt="Dein Profilbild"/>:<span>{profile.firstName[0]}{profile.lastName[0]}</span>}</div><div className="avatar-copy"><h3>{profile.firstName} {profile.lastName}</h3><p>{profile.email}</p><div className="avatar-actions"><label className="avatar-file-action">{busy?"Bitte warten …":profile.profileImage?"Bild ersetzen":"Bild auswählen"}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={selectAvatar} disabled={busy}/></label>{profile.profileImage&&<button type="button" onClick={deleteAvatar} disabled={busy}>Löschen</button>}</div><small>JPEG, PNG oder WebP · maximal 5 MB</small></div><aside className="profile-qr"><small>Beim Kursbesuch vorzeigen</small><img src="/api/me/qr" alt="Persönlicher QR-Code für die Anwesenheit"/></aside></section>
    <section className="profile-auto-section"><div><b>Persönliche Angaben</b><small>{savingProfile?"Wird gespeichert …":"Änderungen werden automatisch gespeichert"}</small></div><form onChange={e=>scheduleProfile(e.currentTarget)}><div className="form-row"><label>Vorname<input name="firstName" defaultValue={profile.firstName} required/></label><label>Nachname<input name="lastName" defaultValue={profile.lastName} required/></label></div><div className="form-row"><label>Geburtstag <small>optional</small><input name="birthday" type="date" defaultValue={profile.birthday||""}/></label><label>Telefon <small>optional</small><input name="phone" type="tel" defaultValue={profile.phone||""}/></label></div></form></section>
    <button onClick={()=>open("email")}>E-Mail-Adresse <span className="profile-value">{profile.email}</span><span>›</span></button>
    {section==="email"&&<form onSubmit={changeEmail}><p className="form-hint">Zum Schutz deines Kontos bestätigst du eine neue E-Mail-Adresse mit deinem aktuellen Passwort. Danach erhältst du einen neuen Bestätigungslink.</p><label>Neue E-Mail-Adresse<input name="email" type="email" defaultValue={profile.email} required autoComplete="email"/></label><label>Aktuelles Passwort<input name="currentPassword" type="password" required autoComplete="current-password"/></label><button className="primary" disabled={busy}>{busy?"Wird geändert …":"E-Mail-Adresse ändern"}</button></form>}
    <button onClick={()=>open("password")}>Passwort ändern<span>›</span></button>
    {section==="password"&&<form onSubmit={changePassword}><p className="form-hint">Nach der Änderung wirst du aus Sicherheitsgründen abgemeldet.</p><label>Aktuelles Passwort<input name="currentPassword" type="password" required autoComplete="current-password"/></label><label>Neues Passwort <small>mindestens 12 Zeichen</small><input name="newPassword" type="password" minLength={12} required autoComplete="new-password"/></label><label>Neues Passwort wiederholen<input name="confirmation" type="password" minLength={12} required autoComplete="new-password"/></label><button className="primary" disabled={busy}>{busy?"Wird geändert …":"Passwort ändern"}</button></form>}
    <PushPreference/>
    <button className="profile-mail-action" onClick={verifyEmail} disabled={busy}><span><b>Bestätigungsmail senden</b><small>Die E-Mail wird sofort versendet</small></span><i aria-hidden="true">✉</i></button>
    <a className="profile-action" href="/api/me/export">Meine Daten herunterladen<span>↓</span></a>
    <button onClick={()=>open("privacy")}>Konto anonymisieren<span>›</span></button>
    {section==="privacy"&&<form className="danger-zone" onSubmit={anonymize}><p>Deine persönlichen Daten und Kurszugänge werden unwiderruflich entfernt. Gesetzlich aufzubewahrende Anwesenheitsnachweise bleiben nur unter einer pseudonymen Referenz erhalten.</p><label>Aktuelles Passwort<input name="currentPassword" type="password" required/></label><label>Zur Bestätigung „KONTO LÖSCHEN“ eingeben<input name="confirmation" pattern="KONTO LÖSCHEN" required/></label><button disabled={busy}>Konto endgültig anonymisieren</button></form>}
    {notice&&<p className="profile-notice" role="status" aria-live="polite">{notice}</p>}
  </div>
}
