"use client";
import { useEffect } from "react";

const limits:Record<string,{minLength?:number;maxLength?:number;min?:number;max?:number}>={title:{minLength:2,maxLength:160},description:{maxLength:5000},location:{maxLength:240},firstName:{minLength:1,maxLength:100},lastName:{minLength:1,maxLength:100},phone:{maxLength:40},count:{min:1,max:500},sessionCount:{min:1,max:100},durationMinutes:{min:15,max:600},sequence:{min:1,max:100},threshold:{min:1,max:100},sessionSequence:{min:1,max:100}};
type Field=HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement;
function message(input:Field){if(input.validity.valueMissing)return "Dieses Feld wird benötigt.";if(input.validity.typeMismatch)return "Bitte gib einen Wert im erwarteten Format ein.";if(input.validity.patternMismatch)return "Die Eingabe entspricht noch nicht dem vorgegebenen Format.";if(input.validity.tooShort&&!(input instanceof HTMLSelectElement))return `Bitte gib mindestens ${input.minLength} Zeichen ein.`;if(input.validity.tooLong&&!(input instanceof HTMLSelectElement))return `Bitte verwende höchstens ${input.maxLength} Zeichen.`;if(input.validity.rangeUnderflow&&input instanceof HTMLInputElement)return `Der kleinste erlaubte Wert ist ${input.min}.`;if(input.validity.rangeOverflow&&input instanceof HTMLInputElement)return `Der größte erlaubte Wert ist ${input.max}.`;return "Bitte prüfe diese Eingabe."}
function showError(input:Field){input.setAttribute("aria-invalid","true");input.classList.add("field-invalid");let error=input.parentElement?.querySelector<HTMLElement>(".field-error");if(!error){error=document.createElement("small");error.className="field-error";error.setAttribute("role","alert");input.insertAdjacentElement("afterend",error)}error.textContent=message(input)}
function clearError(input:Element){input.removeAttribute("aria-invalid");input.classList.remove("field-invalid");input.parentElement?.querySelector(".field-error")?.remove()}
function classify(element:Element){const text=(element.textContent||"").toLowerCase();element.classList.remove("feedback-success","feedback-error","feedback-warning","feedback-info");const error=/fehler|fehlgeschlagen|ungültig|nicht möglich|nicht gefunden|prüfe|fehlt|abgelehnt/.test(text),warning=/warn|achtung|unwiderruf|endgültig|archiv|juristisch/.test(text),success=/gespeichert|erfolgreich|aktiv|versendet|erstellt|synchronisiert|veröffentlicht/.test(text);element.classList.add(error?"feedback-error":warning?"feedback-warning":success?"feedback-success":"feedback-info");element.setAttribute("role",error?"alert":"status");element.setAttribute("aria-live",error?"assertive":"polite")}
function conditional(form:HTMLFormElement){const kind=form.elements.namedItem("kind") as HTMLSelectElement|null,rule=form.elements.namedItem("ruleType") as HTMLSelectElement|null;const toggle=(name:string,show:boolean,required=false)=>{const field=form.elements.namedItem(name) as HTMLInputElement|HTMLTextAreaElement|null,label=field?.closest("label");if(!field||!label)return;label.classList.toggle("conditional-hidden",!show);field.disabled=!show;field.required=show&&required};if(kind){const value=kind.value;toggle("body",value==="text",value==="text");toggle("externalUrl",["youtube","vimeo","link"].includes(value),["youtube","vimeo","link"].includes(value));toggle("file",["image","pdf","video"].includes(value),["image","pdf","video"].includes(value))}if(rule){toggle("threshold",rule.value==="attendance_count",rule.value==="attendance_count");toggle("sessionSequence",rule.value==="session",rule.value==="session")}}

export function useAdminFormUx(){useEffect(()=>{const root=document.querySelector<HTMLElement>(".real-admin");if(!root)return;const enhance=()=>{root.querySelectorAll<HTMLInputElement>("input[name]").forEach(input=>{const rule=limits[input.name];if(!rule)return;if(rule.minLength)input.minLength=rule.minLength;if(rule.maxLength)input.maxLength=rule.maxLength;if(rule.min!==undefined)input.min=String(rule.min);if(rule.max!==undefined)input.max=String(rule.max)});root.querySelectorAll<HTMLTextAreaElement>("textarea[name]").forEach(input=>{const rule=limits[input.name];if(rule?.maxLength)input.maxLength=rule.maxLength});root.querySelectorAll<HTMLFormElement>("form").forEach(conditional);root.querySelectorAll(".admin-notice,.form-error,.legal-warning,[role=status]").forEach(classify)};enhance();const invalid=(event:Event)=>{const field=event.target;if(field instanceof HTMLInputElement||field instanceof HTMLTextAreaElement||field instanceof HTMLSelectElement)showError(field)},input=(event:Event)=>{if(event.target instanceof Element)clearError(event.target);const form=(event.target as Element)?.closest?.("form");if(form)conditional(form)},submit=(event:Event)=>{const form=event.target;if(!(form instanceof HTMLFormElement))return;form.querySelectorAll<Field>("input,textarea,select").forEach(field=>{if(!field.checkValidity())showError(field)});if(!form.checkValidity())form.querySelector<HTMLElement>(".field-invalid")?.focus()};root.addEventListener("invalid",invalid,true);root.addEventListener("input",input);root.addEventListener("change",input);root.addEventListener("submit",submit);const observer=new MutationObserver(enhance);observer.observe(root,{subtree:true,childList:true,characterData:true});return()=>{observer.disconnect();root.removeEventListener("invalid",invalid,true);root.removeEventListener("input",input);root.removeEventListener("change",input);root.removeEventListener("submit",submit)}},[])}
