"use client";
/* Private QR images intentionally bypass public image optimization. */
/* eslint-disable @next/next/no-img-element */
import {useEffect,useRef,useState} from "react";

type Session={title:string;startsAt:string;endsAt:string;location:string|null};
type WakeLockHandle={release:()=>Promise<void>};
const icsDate=(value:string)=>new Date(value).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");
export function CalendarAction({session}:{session:Session}){function download(){const escape=(value:string)=>value.replace(/([,;\\])/g,"\\$1").replace(/\n/g,"\\n"),ics=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Staerke deine Mitte//Termine//DE","BEGIN:VEVENT",`UID:${crypto.randomUUID()}@app.anja-tanzt.de`,`DTSTAMP:${icsDate(new Date().toISOString())}`,`DTSTART:${icsDate(session.startsAt)}`,`DTEND:${icsDate(session.endsAt)}`,`SUMMARY:${escape(session.title)}`,`LOCATION:${escape(session.location||"")}`,"END:VEVENT","END:VCALENDAR",""] .join("\r\n"),url=URL.createObjectURL(new Blob([ics],{type:"text/calendar;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`${session.title.replace(/[^a-z0-9äöüß]+/gi,"-").replace(/^-|-$/g,"")||"Termin"}.ics`;link.click();URL.revokeObjectURL(url)}return <button type="button" className="calendar-action" onClick={download}>Zum Kalender hinzufügen</button>}

export function QuickAttendanceQr(){const [open,setOpen]=useState(false),[wake,setWake]=useState(false),lock=useRef<WakeLockHandle|null>(null);async function show(){setOpen(true);try{const manager=(navigator as Navigator&{wakeLock?:{request:(type:"screen")=>Promise<WakeLockHandle>}}).wakeLock;if(manager){lock.current=await manager.request("screen");setWake(true)}}catch{setWake(false)}}async function close(){setOpen(false);await lock.current?.release().catch(()=>undefined);lock.current=null;setWake(false)}useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=previous;void lock.current?.release()}},[open]);return <><button type="button" className="primary quick-qr-button" onClick={show}><span aria-hidden="true">▦</span> Teilnahme-QR öffnen</button>{open&&<div className="qr-presenter" role="dialog" aria-modal="true" aria-labelledby="quick-qr-title"><button type="button" className="qr-presenter-close" onClick={()=>void close()} aria-label="QR-Code schließen">×</button><div className="qr-presenter-content"><p className="eyebrow">Heute beim Kurs vorzeigen</p><h2 id="quick-qr-title">Dein Teilnahme-QR</h2><div className="qr-presenter-code"><img src="/api/me/qr" alt="Persönlicher QR-Code für die Anwesenheit"/></div><p>Halte den Code ruhig und vollständig vor die Kamera der Kursleitung.</p><small>{wake?"Der Bildschirm bleibt während der Anzeige aktiv.":"Erhöhe bei Bedarf kurz die Gerätehelligkeit."}</small></div></div>}</>}
