"use client";
import { ComponentType, useEffect, useState } from "react";

export type DashboardCourse={id:string;title:string;description:string;sessionCount:number;durationMinutes:number;startsAt:string|null;endsAt:string|null;location:string|null;navigationUrl:string|null;treeVariant:string;completedAt:string|null;attendedCount:number};
export type DashboardSession={id:string;courseId:string;sequence:number;title:string;startsAt:string;endsAt:string;location:string|null;navigationUrl:string|null};
export type Dashboard={user:{firstName:string};courses:DashboardCourse[];upcoming:DashboardSession[]};

export function useDashboard(enabled:boolean){const [data,setData]=useState<Dashboard|null>(null);useEffect(()=>{if(enabled)fetch("/api/dashboard").then(r=>r.ok?r.json():null).then(setData)},[enabled]);return data;}

export function RealCourses({data,Tree}:{data:Dashboard;Tree:ComponentType<{progress?:number}>}){
  const active=data.courses.filter(c=>!c.completedAt),past=data.courses.filter(c=>c.completedAt);
  return <main className="page shell"><p className="eyebrow">Dein persönlicher Weg</p><h1>Meine Kurse</h1>{!data.courses.length&&<div className="empty-state"><h2>Noch kein Kurs</h2><p>Löse im Profil einen Zugangscode ein, sobald du deinen Kurs gebucht hast.</p></div>}{active.map(c=><div className="course-card real-course" key={c.id}><div className="course-art"><Tree progress={c.attendedCount}/></div><div className="course-info"><span className="active-pill">Aktiver Kurs</span><h2>{c.title}</h2><p>{c.sessionCount} × {c.durationMinutes} Minuten · {c.location||"Ort folgt"}</p><div className="stamp-grid">{Array.from({length:c.sessionCount},(_,i)=><div className={i<c.attendedCount?"stamp done":"stamp"} key={i}><b>{i<c.attendedCount?"✓":i+1}</b><span>Einheit {i+1}</span></div>)}</div><p>{c.attendedCount} von {c.sessionCount} gemeinsamen Einheiten</p></div></div>)}{past.length>0&&<><h2 className="section-title">Vergangene Kurse</h2>{past.map(c=><div className="past-course" key={c.id}><div><small>Abgeschlossen · {new Date(c.completedAt!).toLocaleDateString("de-DE")}</small><h3>{c.title}</h3><p>{c.sessionCount} gemeinsame Einheiten</p></div><span className="event-star">✦</span></div>)}</>}</main>;
}

export function RealDates({data}:{data:Dashboard}){return <main className="page shell"><p className="eyebrow">Gemeinsame Zeit</p><h1>Meine Termine</h1><div className="timeline">{data.upcoming.map((s,i)=>{const d=new Date(s.startsAt);return <article className={i===0?"next":""} key={s.id}><div className="date-tile"><b>{d.getDate()}</b><span>{d.toLocaleDateString("de-DE",{month:"short"})}</span></div><div><small>{i===0?"DEIN NÄCHSTER TERMIN":`EINHEIT ${s.sequence}`}</small><h2>{s.title}</h2><p>{d.toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})} Uhr · {s.location||"Ort folgt"}</p></div>{s.navigationUrl&&<a href={s.navigationUrl} target="_blank" rel="noreferrer">↗</a>}</article>})}</div>{!data.upcoming.length&&<div className="empty-state"><h2>Im Moment stehen keine Termine an.</h2><p>Neue Termine erscheinen hier automatisch.</p></div>}<h2 className="section-title">Weitere Veranstaltungen</h2><a className="event" href="https://anja-tanzt.de" target="_blank" rel="noreferrer"><span>✦</span><div><small>ENTDECKEN</small><h2>Zeit für mich</h2><p>Alle kommenden besonderen Veranstaltungen bei Anja tanzt.</p></div></a></main>}
