"use client";
/* User-uploaded media is protected by authenticated routes, so framework image optimization is intentionally bypassed. */
/* eslint-disable @next/next/no-img-element, jsx-a11y/media-has-caption */
import { ComponentType, useEffect, useState } from "react";

export type DashboardCourse={id:string;title:string;description:string;sessionCount:number;durationMinutes:number;startsAt:string|null;endsAt:string|null;location:string|null;navigationUrl:string|null;treeVariant:string;completedAt:string|null;attendedCount:number};
export type DashboardSession={id:string;courseId:string;sequence:number;title:string;startsAt:string;endsAt:string;location:string|null;navigationUrl:string|null};
export type Dashboard={user:{firstName:string};courses:DashboardCourse[];upcoming:DashboardSession[]};
type CourseContent={id:string;title:string;kind:string;body:string|null;assetPath:string|null;externalUrl:string|null;contentUpdatedAt:string};
type PublicEvent={id:string;title:string;description:string;startsAt:string;location:string|null;navigationUrl:string|null;shopUrl:string|null};

export function useDashboard(enabled:boolean){const [data,setData]=useState<Dashboard|null>(null);useEffect(()=>{if(enabled)fetch("/api/dashboard").then(r=>r.ok?r.json():null).then(setData)},[enabled]);return data;}

export function RealCourses({data,Tree}:{data:Dashboard;Tree:ComponentType<{progress?:number}>}){
  const [open,setOpen]=useState<string|null>(null),[items,setItems]=useState<CourseContent[]>([]),[consented,setConsented]=useState<Record<string,boolean>>({});
  useEffect(()=>{if(open)fetch(`/api/courses/${open}/content`).then(r=>r.json()).then(result=>setItems(result.items||[]))},[open]);
  const active=data.courses.filter(c=>!c.completedAt),past=data.courses.filter(c=>c.completedAt);
  const render=(item:CourseContent)=>{const media=item.assetPath?`/api/media/${item.assetPath}`:"";if(item.kind==="image")return <img src={media} alt=""/>;if(item.kind==="pdf")return <iframe src={media} title={item.title}/>;if(item.kind==="video")return <video controls preload="metadata" src={media}/>;if(item.kind==="youtube"||item.kind==="vimeo"){if(!consented[item.id])return <div className="video-consent"><p>Beim Laden wird eine Verbindung zu {item.kind==="youtube"?"YouTube":"Vimeo"} hergestellt. Dabei können Daten an den Anbieter übertragen werden.</p><button className="primary" onClick={()=>setConsented(x=>({...x,[item.id]:true}))}>Video zustimmen & laden</button></div>;const url=item.externalUrl||"",embed=item.kind==="youtube"?`https://www.youtube-nocookie.com/embed/${url.split("v=")[1]?.split("&")[0]||url.split("/").pop()}`:`https://player.vimeo.com/video/${url.split("/").pop()}`;return <iframe src={embed} title={item.title} allowFullScreen/>}if(item.kind==="link")return <a className="primary content-link" href={item.externalUrl||"#"} target="_blank" rel="noreferrer">Link öffnen ↗</a>;return null};
  return <main className="page shell"><p className="eyebrow">Dein persönlicher Weg</p><h1>Meine Kurse</h1>{!data.courses.length&&<div className="empty-state"><h2>Noch kein Kurs</h2><p>Löse im Profil einen Zugangscode ein, sobald du deinen Kurs gebucht hast.</p></div>}{active.map(c=><div className="course-card real-course" key={c.id}><div className="course-art"><Tree progress={c.attendedCount}/></div><div className="course-info"><span className="active-pill">Aktiver Kurs</span><h2>{c.title}</h2><p>{c.sessionCount} × {c.durationMinutes} Minuten · {c.location||"Ort folgt"}</p><div className="stamp-grid">{Array.from({length:c.sessionCount},(_,i)=><div className={i<c.attendedCount?"stamp done":"stamp"} key={i}><b>{i<c.attendedCount?"✓":i+1}</b><span>Einheit {i+1}</span></div>)}</div><p>{c.attendedCount} von {c.sessionCount} gemeinsamen Einheiten</p><button className="primary" onClick={()=>setOpen(open===c.id?null:c.id)}>{open===c.id?"Inhalte schließen":"Kurs öffnen"}</button></div>{open===c.id&&<section className="course-content">{items.map(item=><article key={item.id}><small>STAND {new Date(item.contentUpdatedAt).toLocaleString("de-DE")}</small><h3>{item.title}</h3>{item.body&&<p>{item.body}</p>}{render(item)}</article>)}{!items.length&&<p>Für deinen aktuellen Stand sind noch keine Materialien freigeschaltet.</p>}</section>}</div>)}{past.length>0&&<><h2 className="section-title">Vergangene Kurse</h2>{past.map(c=><div className="past-course" key={c.id}><div><small>Abgeschlossen · {new Date(c.completedAt!).toLocaleDateString("de-DE")}</small><h3>{c.title}</h3><p>{c.sessionCount} gemeinsame Einheiten</p></div><span className="event-star">✦</span></div>)}</>}</main>;
}

export function RealDates({data}:{data:Dashboard}){const [events,setEvents]=useState<PublicEvent[]>([]);useEffect(()=>{fetch("/api/events").then(r=>r.json()).then(x=>setEvents(x.events||[]))},[]);return <main className="page shell"><p className="eyebrow">Gemeinsame Zeit</p><h1>Meine Termine</h1><div className="timeline">{data.upcoming.map((s,i)=>{const d=new Date(s.startsAt);return <article className={i===0?"next":""} key={s.id}><div className="date-tile"><b>{d.getDate()}</b><span>{d.toLocaleDateString("de-DE",{month:"short"})}</span></div><div><small>{i===0?"DEIN NÄCHSTER TERMIN":`EINHEIT ${s.sequence}`}</small><h2>{s.title}</h2><p>{d.toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})} Uhr · {s.location||"Ort folgt"}</p></div>{s.navigationUrl&&<a href={s.navigationUrl} target="_blank" rel="noreferrer">↗</a>}</article>})}</div>{!data.upcoming.length&&<div className="empty-state"><h2>Im Moment stehen keine Termine an.</h2><p>Neue Termine erscheinen hier automatisch.</p></div>}<h2 className="section-title">Weitere Veranstaltungen</h2>{events.map(event=><article className="event" key={event.id}><span>✦</span><div><small>{new Date(event.startsAt).toLocaleDateString("de-DE")}</small><h2>{event.title}</h2><p>{event.description} {event.location&&`· ${event.location}`}</p></div>{event.navigationUrl&&<a href={event.navigationUrl} target="_blank" rel="noreferrer">Navi ↗</a>}{event.shopUrl&&<a href={event.shopUrl} target="_blank" rel="noreferrer">Buchen ↗</a>}</article>)}{!events.length&&<a className="event" href="https://anja-tanzt.de" target="_blank" rel="noreferrer"><span>✦</span><div><small>ENTDECKEN</small><h2>Zeit für mich</h2><p>Alle kommenden besonderen Veranstaltungen bei Anja tanzt.</p></div></a>}</main>}
