import fs from "node:fs/promises";
import path from "node:path";
import {createWriteStream} from "node:fs";
import {Readable} from "node:stream";
import {pipeline} from "node:stream/promises";
import {requireAdmin} from "@/lib/auth";
import {audit,db,id,now} from "@/lib/database";
import {mediaDir,safeStoredName,validateMedia,validSignature} from "@/lib/media";
export const runtime="nodejs";
async function save(adminId:string,file:{name:string;type:string;size:number},data?:Uint8Array,body?:ReadableStream<Uint8Array>){const error=validateMedia(file);if(error)return Response.json({error},{status:400});const storedName=safeStoredName(file as File),target=path.join(mediaDir,storedName),mediaId=id();try{if(data)await fs.writeFile(target,data,{mode:0o600,flag:"wx"});else if(body){let received=0;const source=Readable.fromWeb(body as never);source.on("data",chunk=>{received+=chunk.length;if(received>file.size)source.destroy(new Error("Upload größer als angekündigt"))});await pipeline(source,createWriteStream(target,{mode:0o600,flags:"wx"}));if(received!==file.size)throw new Error("Uploadgröße stimmt nicht")}const handle=await fs.open(target,"r"),header=Buffer.alloc(16);await handle.read(header,0,16,0);await handle.close();if(!validSignature(file.type,header))throw new Error("Dateisignatur passt nicht zum Dateityp");db.prepare("INSERT INTO media_files (id,owner_id,original_name,stored_name,mime_type,size_bytes,created_at) VALUES (?,?,?,?,?,?,?)").run(mediaId,adminId,file.name,storedName,file.type,file.size,now());audit(adminId,"media.upload","media",mediaId,{name:file.name,type:file.type,size:file.size});return Response.json({id:mediaId,name:file.name,type:file.type,size:file.size},{status:201})}catch(error){await fs.rm(target,{force:true});return Response.json({error:error instanceof Error?`Datei abgelehnt: ${error.message}`:"Die Datei konnte nicht sicher gespeichert werden."},{status:400})}}
export async function POST(request:Request){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});if(request.headers.get("content-type")==="application/octet-stream"){const name=decodeURIComponent(request.headers.get("x-file-name")||""),type=request.headers.get("x-file-type")||"",size=Number(request.headers.get("x-file-size")||request.headers.get("content-length")||0);if(!request.body||!name||!Number.isSafeInteger(size))return Response.json({error:"Uploadangaben fehlen."},{status:400});return save(admin.id,{name,type,size},undefined,request.body)}const form=await request.formData(),file=form.get("file");if(!(file instanceof File))return Response.json({error:"Keine Datei empfangen."},{status:400});if(file.size>25*1024*1024)return Response.json({error:"Große Videos werden ausschließlich über den sicheren Streaming-Upload angenommen."},{status:413});return save(admin.id,file,new Uint8Array(await file.arrayBuffer()))}
