import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { audit,db,now } from "@/lib/database";
const defaults={accountMinimumMonths:24,attendanceArchiveMonths:120,expiredTokenDays:7};
const schema=z.object({accountMinimumMonths:z.number().int().min(24).max(240),attendanceArchiveMonths:z.number().int().min(120).max(600),expiredTokenDays:z.number().int().min(1).max(90)});
function settings(){const row=db.prepare("SELECT value FROM app_settings WHERE key='retention'").get() as {value:string}|undefined;return row?{...defaults,...JSON.parse(row.value)}:defaults}
export async function GET(){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const counts={expiredTokens:(db.prepare("SELECT COUNT(*) count FROM account_tokens WHERE expires_at<?").get(now()) as {count:number}).count,oldAttendanceArchives:(db.prepare("SELECT COUNT(*) count FROM attendance_archive WHERE archived_at<datetime('now',?)").get(`-${settings().attendanceArchiveMonths} months`) as {count:number}).count};return Response.json({settings:settings(),counts})}
export async function POST(request:Request){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Mindestens 24 Monate für App-Daten und 120 Monate für Anwesenheitsarchive."},{status:400});db.prepare("INSERT INTO app_settings (key,value,updated_at) VALUES ('retention',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").run(JSON.stringify(parsed.data),now());audit(admin.id,"retention.update","settings","retention",parsed.data);return Response.json({ok:true})}
export async function DELETE(request:Request){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const body=await request.json().catch(()=>null);if(body?.confirmation!=="FRISTEN ANWENDEN")return Response.json({error:"Bestätigung fehlt."},{status:400});const value=settings(),tokenCutoff=`-${value.expiredTokenDays} days`,attendanceCutoff=`-${value.attendanceArchiveMonths} months`;const result=db.transaction(()=>({tokens:db.prepare("DELETE FROM account_tokens WHERE expires_at<datetime('now',?)").run(tokenCutoff).changes,attendanceArchives:db.prepare("DELETE FROM attendance_archive WHERE archived_at<datetime('now',?)").run(attendanceCutoff).changes,loginAttempts:db.prepare("DELETE FROM login_attempts WHERE window_started_at<datetime('now','-90 days')").run().changes,requestLimits:db.prepare("DELETE FROM request_limits WHERE window_started_at<datetime('now','-2 days')").run().changes,push:db.prepare("DELETE FROM push_subscriptions WHERE enabled=0 AND updated_at<datetime('now','-90 days')").run().changes}))();audit(admin.id,"retention.apply","settings","retention",result);return Response.json({ok:true,result})}
