import {audit,db,id,now} from "@/lib/database";
import {sendMail,smtpErrorMessage,smtpSettings} from "@/lib/mail";
import {configuredTimeZone} from "@/lib/timezone-settings";

type QueueInput={to:string;subject:string;text:string;kind:string;batchId?:string|null;codeHint?:string|null;createdBy?:string|null};
type Job={id:string;batchId:string|null;kind:string;recipient:string;subject:string;bodyText:string;codeHint:string|null;attempts:number;maxAttempts:number};

export function enqueueMail(input:QueueInput){const jobId=id(),timestamp=now();db.prepare("INSERT INTO mail_queue (id,batch_id,kind,recipient,subject,body_text,code_hint,status,attempts,max_attempts,available_at,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'queued',0,5,?,?,?,?)").run(jobId,input.batchId||null,input.kind,input.to.trim().toLowerCase(),input.subject,input.text,input.codeHint||null,timestamp,input.createdBy||null,timestamp,timestamp);return jobId}
export function createMailBatch(courseId:string,courseTitle:string,createdBy:string){const batchId=id();db.prepare("INSERT INTO mail_batches (id,course_id,course_title,created_by,created_at) VALUES (?,?,?,?,?)").run(batchId,courseId,courseTitle,createdBy,now());return batchId}

function claim():Job|null{return db.transaction(()=>{const timestamp=now(),stale=new Date(Date.now()-10*60_000).toISOString();db.prepare("UPDATE mail_queue SET status='failed',available_at=?,last_error='Versandprozess wurde unterbrochen und automatisch wieder aufgenommen.',updated_at=? WHERE status='processing' AND updated_at<?").run(timestamp,timestamp,stale);const row=db.prepare(`SELECT id,batch_id batchId,kind,recipient,subject,body_text bodyText,code_hint codeHint,attempts,max_attempts maxAttempts FROM mail_queue WHERE status IN ('queued','failed') AND attempts<max_attempts AND available_at<=? ORDER BY created_at LIMIT 1`).get(timestamp) as Job|undefined;if(!row)return null;const changed=db.prepare("UPDATE mail_queue SET status='processing',attempts=attempts+1,updated_at=? WHERE id=? AND status IN ('queued','failed')").run(timestamp,row.id).changes;return changed?{...row,attempts:row.attempts+1}:null})()}
function retryAt(attempt:number){return new Date(Date.now()+Math.min(24*60,Math.pow(4,attempt)*5)*60_000).toISOString()}

function queueFinishedBatchSummaries(){const batches=db.prepare(`SELECT b.id,b.course_title courseTitle,b.created_by createdBy,b.created_at createdAt FROM mail_batches b WHERE b.summary_queued_at IS NULL AND EXISTS (SELECT 1 FROM mail_queue q WHERE q.batch_id=b.id) AND NOT EXISTS (SELECT 1 FROM mail_queue q WHERE q.batch_id=b.id AND q.status!='sent' AND q.attempts<q.max_attempts)`).all() as {id:string;courseTitle:string;createdBy:string|null;createdAt:string}[];for(const batch of batches){const rows=db.prepare("SELECT recipient,code_hint codeHint,status,attempts,sent_at sentAt,last_error lastError FROM mail_queue WHERE batch_id=? ORDER BY created_at").all(batch.id) as {recipient:string;codeHint:string|null;status:string;attempts:number;sentAt:string|null;lastError:string|null}[],sent=rows.filter(row=>row.status==="sent").length,failed=rows.length-sent,admins=db.prepare("SELECT email FROM users WHERE role='admin' AND status='active'").all() as {email:string}[],lines=rows.map(row=>`${row.sentAt?new Date(row.sentAt).toLocaleString("de-DE",{timeZone:configuredTimeZone()}):"Nicht versendet"} · ${row.recipient} · Code ••••-${row.codeHint||"????"} · ${row.status==="sent"?"vom Mailserver angenommen":`nach ${row.attempts} Versuchen fehlgeschlagen: ${row.lastError||"Unbekannter SMTP-Fehler"}`}`).join("\n"),text=`Der Einladungsversand für „${batch.courseTitle}“ ist abgeschlossen.\n\nErfolgreich versendet: ${sent}\nEndgültig fehlgeschlagen: ${failed}\n\nVERSANDPROTOKOLL\n${lines}\n\nDie vollständigen Zugangscodes sind aus Sicherheitsgründen nicht Bestandteil dieses Berichts.`;for(const admin of admins)enqueueMail({to:admin.email,subject:"Stärke deine Mitte · Versandbericht der Kurszugänge",text,kind:"batch_summary",createdBy:batch.createdBy});db.prepare("UPDATE mail_batches SET summary_queued_at=? WHERE id=?").run(now(),batch.id);audit(batch.createdBy,"mail.batch_complete","mail_batch",batch.id,{sent,failed,summaryRecipients:admins.length})}}

export async function processMailQueue(limit=25){if(!smtpSettings())return {processed:0,sent:0,failed:0,configurationError:"SMTP ist noch nicht eingerichtet."};let processed=0,sent=0,failed=0;for(;processed<limit;processed++){const job=claim();if(!job)break;try{await sendMail({to:job.recipient,subject:job.subject,text:job.bodyText});const sentAt=now();db.prepare("UPDATE mail_queue SET status='sent',sent_at=?,last_error=NULL,updated_at=? WHERE id=?").run(sentAt,sentAt,job.id);audit(null,"mail.sent","mail",job.id,{recipient:job.recipient,kind:job.kind,codeHint:job.codeHint,batchId:job.batchId,attempt:job.attempts});sent++}catch(error){const message=smtpErrorMessage(error),terminal=job.attempts>=job.maxAttempts;db.prepare("UPDATE mail_queue SET status='failed',available_at=?,last_error=?,updated_at=? WHERE id=?").run(terminal?now():retryAt(job.attempts),message,now(),job.id);audit(null,terminal?"mail.failed":"mail.retry_scheduled","mail",job.id,{recipient:job.recipient,kind:job.kind,codeHint:job.codeHint,batchId:job.batchId,attempt:job.attempts,error:message});failed++}}queueFinishedBatchSummaries();return {processed,sent,failed}}

export function retryMail(idValue:string,actorId:string){const result=db.prepare("UPDATE mail_queue SET status='queued',attempts=0,available_at=?,last_error=NULL,updated_at=? WHERE id=? AND status='failed'").run(now(),now(),idValue);if(result.changes)audit(actorId,"mail.retry_manual","mail",idValue);return Boolean(result.changes)}
