import { db,now } from "@/lib/database";
import { generateAuthenticationOptions,verifyAuthenticationResponse } from "@simplewebauthn/server";
import type { AuthenticationResponseJSON,AuthenticatorTransportFuture } from "@simplewebauthn/server";

export function passkeyConfig(){const configured=process.env.APP_URL;if(!configured)throw new Error("APP_URL muss für Passkeys gesetzt sein.");const url=new URL(configured);if(url.protocol!=="https:"&&url.hostname!=="localhost")throw new Error("Passkeys benötigen HTTPS.");return {origin:url.origin,rpID:url.hostname,rpName:"Mein Kraftbaum"}}
export function saveChallenge(userId:string,challenge:string,purpose:"registration"|"authentication"){db.prepare("INSERT INTO passkey_challenges (user_id,challenge,purpose,expires_at) VALUES (?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET challenge=excluded.challenge,purpose=excluded.purpose,expires_at=excluded.expires_at").run(userId,challenge,purpose,new Date(Date.now()+5*60_000).toISOString())}
export function takeChallenge(userId:string,purpose:"registration"|"authentication"){const row=db.prepare("SELECT challenge FROM passkey_challenges WHERE user_id=? AND purpose=? AND expires_at>?").get(userId,purpose,now()) as {challenge:string}|undefined;if(row)db.prepare("DELETE FROM passkey_challenges WHERE user_id=?").run(userId);return row?.challenge||null}
type Stored={id:string;publicKey:string;counter:number;transports:string};
export async function beginPasskeyAuthentication(userId:string){const config=passkeyConfig(),credentials=db.prepare("SELECT id,public_key publicKey,counter,transports FROM passkey_credentials WHERE user_id=?").all(userId) as Stored[];if(!credentials.length)throw new Error("Für dieses Konto ist kein Passkey hinterlegt.");const options=await generateAuthenticationOptions({rpID:config.rpID,userVerification:"required",allowCredentials:credentials.map(x=>({id:x.id,transports:JSON.parse(x.transports)}))});saveChallenge(userId,options.challenge,"authentication");return options}
export async function finishPasskeyAuthentication(userId:string,response:AuthenticationResponseJSON){const challenge=takeChallenge(userId,"authentication");if(!challenge)return false;const row=db.prepare("SELECT id,public_key publicKey,counter,transports FROM passkey_credentials WHERE id=? AND user_id=?").get(response.id,userId) as Stored|undefined;if(!row)return false;const config=passkeyConfig(),result=await verifyAuthenticationResponse({response,expectedChallenge:challenge,expectedOrigin:config.origin,expectedRPID:config.rpID,credential:{id:row.id,publicKey:Buffer.from(row.publicKey,"base64url"),counter:row.counter,transports:JSON.parse(row.transports) as AuthenticatorTransportFuture[]},requireUserVerification:true});if(!result.verified)return false;db.prepare("UPDATE passkey_credentials SET counter=?,last_used_at=? WHERE id=?").run(result.authenticationInfo.newCounter,now(),row.id);return true}
