import { z } from "zod";
import { requireAdmin, verifyQrToken } from "@/lib/auth";
import { audit, db, id, now } from "@/lib/database";
import { refreshCompletion } from "@/lib/progress";

const addSchema=z.object({userId:z.string().uuid().optional(),qrToken:z.string().min(20).optional(),sessionId:z.string().uuid(),source:z.enum(["list","scan","paper","makeup"]),note:z.string().max(500).optional()}).refine(x=>Boolean(x.userId||x.qrToken));
const removeSchema=z.object({userId:z.string().uuid(),sessionId:z.string().uuid(),reason:z.string().min(3).max(500)});
export async function POST(request:Request){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const parsed=addSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Bitte prüfe die Anwesenheitsdaten."},{status:400});const userId=parsed.data.userId||(parsed.data.qrToken?await verifyQrToken(parsed.data.qrToken):null);if(!userId)return Response.json({error:"Der QR-Code ist ungültig oder abgelaufen."},{status:400});const session=db.prepare("SELECT course_id courseId FROM course_sessions WHERE id=?").get(parsed.data.sessionId) as {courseId:string}|undefined;if(!session||!db.prepare("SELECT 1 FROM enrollments WHERE user_id=? AND course_id=?").get(userId,session.courseId))return Response.json({error:"Teilnehmer oder Termin ist diesem Kurs nicht zugeordnet."},{status:404});const timestamp=now();db.prepare("INSERT INTO attendance (id,user_id,session_id,recorded_by,source,note,recorded_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id,session_id) DO UPDATE SET recorded_by=excluded.recorded_by,source=excluded.source,note=excluded.note,recorded_at=excluded.recorded_at").run(id(),userId,parsed.data.sessionId,admin.id,parsed.data.source,parsed.data.note||null,timestamp);refreshCompletion(userId,session.courseId);audit(admin.id,"attendance.record","session",parsed.data.sessionId,{userId,source:parsed.data.source});return Response.json({ok:true});}
export async function DELETE(request:Request){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const parsed=removeSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Eine Korrekturbegründung ist erforderlich."},{status:400});const session=db.prepare("SELECT course_id courseId FROM course_sessions WHERE id=?").get(parsed.data.sessionId) as {courseId:string}|undefined;if(!session)return Response.json({error:"Termin nicht gefunden."},{status:404});const result=db.prepare("DELETE FROM attendance WHERE user_id=? AND session_id=?").run(parsed.data.userId,parsed.data.sessionId);if(!result.changes)return Response.json({error:"Keine Anwesenheit gefunden."},{status:404});refreshCompletion(parsed.data.userId,session.courseId);audit(admin.id,"attendance.remove","session",parsed.data.sessionId,{userId:parsed.data.userId,reason:parsed.data.reason});return Response.json({ok:true});}
