import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { audit,db,now } from "@/lib/database";
import { refreshCompletion } from "@/lib/progress";
const schema=z.object({sourceUserId:z.string().uuid(),targetUserId:z.string().uuid(),confirmation:z.literal("KONTEN ZUSAMMENFÜHREN")}).refine(x=>x.sourceUserId!==x.targetUserId);
export async function POST(request:Request){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Bitte wähle zwei verschiedene Konten und bestätige den Vorgang."},{status:400});const {sourceUserId,targetUserId}=parsed.data,source=db.prepare("SELECT role,status FROM users WHERE id=?").get(sourceUserId) as {role:string;status:string}|undefined,target=db.prepare("SELECT role,status FROM users WHERE id=?").get(targetUserId) as {role:string;status:string}|undefined;if(!source||!target)return Response.json({error:"Mindestens ein Konto wurde nicht gefunden."},{status:404});if(source.role==="admin"||target.role==="admin")return Response.json({error:"Administrationskonten können aus Sicherheitsgründen nicht zusammengeführt werden."},{status:409});if(target.status!=="active")return Response.json({error:"Das Zielkonto muss aktiv sein."},{status:409});const timestamp=now();db.transaction(()=>{db.prepare(`INSERT INTO enrollments (id,user_id,course_id,access_mode,tree_variant,completed_at,created_at)
    SELECT lower(hex(randomblob(16))),?,course_id,access_mode,tree_variant,completed_at,created_at FROM enrollments WHERE user_id=?
    ON CONFLICT(user_id,course_id) DO UPDATE SET completed_at=COALESCE(enrollments.completed_at,excluded.completed_at),access_mode=CASE WHEN enrollments.access_mode='full' OR excluded.access_mode='full' THEN 'full' ELSE enrollments.access_mode END`).run(targetUserId,sourceUserId);db.prepare(`INSERT INTO attendance (id,user_id,session_id,recorded_by,source,note,recorded_at)
    SELECT lower(hex(randomblob(16))),?,session_id,recorded_by,source,note,recorded_at FROM attendance WHERE user_id=?
    ON CONFLICT(user_id,session_id) DO NOTHING`).run(targetUserId,sourceUserId);db.prepare(`INSERT INTO manual_unlocks (id,user_id,content_id,granted_by,reason,created_at)
    SELECT lower(hex(randomblob(16))),?,content_id,granted_by,reason,created_at FROM manual_unlocks WHERE user_id=?
    ON CONFLICT(user_id,content_id) DO NOTHING`).run(targetUserId,sourceUserId);db.prepare("UPDATE access_codes SET redeemed_by=? WHERE redeemed_by=?").run(targetUserId,sourceUserId);db.prepare("UPDATE consent_history SET user_id=? WHERE user_id=?").run(targetUserId,sourceUserId);db.prepare("UPDATE push_subscriptions SET user_id=? WHERE user_id=?").run(targetUserId,sourceUserId);db.prepare("DELETE FROM attendance WHERE user_id=?").run(sourceUserId);db.prepare("DELETE FROM manual_unlocks WHERE user_id=?").run(sourceUserId);db.prepare("DELETE FROM enrollments WHERE user_id=?").run(sourceUserId);db.prepare("UPDATE users SET email=?,password_hash='',first_name='Zusammengeführt',last_name='Konto',birthday=NULL,phone=NULL,status='merged',updated_at=? WHERE id=?").run(`merged-${sourceUserId}@invalid.local`,timestamp,sourceUserId)})();const courses=db.prepare("SELECT course_id courseId FROM enrollments WHERE user_id=?").all(targetUserId) as {courseId:string}[];for(const course of courses)refreshCompletion(targetUserId,course.courseId);audit(admin.id,"user.merge","user",targetUserId,{sourceUserId});return Response.json({ok:true})}
