import fs from "node:fs/promises";
import path from "node:path";
import {Readable} from "node:stream";
import {pipeline} from "node:stream/promises";
import {createWriteStream} from "node:fs";
import {execFile} from "node:child_process";
import {promisify} from "node:util";
import {z} from "zod";
import {requireFreshAdmin as requireAdmin} from "@/lib/auth";
import {audit} from "@/lib/database";
const exec=promisify(execFile),dataDir=process.env.DATA_DIR||path.join(process.cwd(),"data"),staging=path.join(dataDir,"restore-staging"),maxBytes=Number(process.env.BACKUP_UPLOAD_MAX_BYTES||20*1024*1024*1024),maxExpandedBytes=Number(process.env.BACKUP_EXPANDED_MAX_BYTES||50*1024*1024*1024);
const safeExtract=`import pathlib,sys,tarfile\narchive,target,limit=sys.argv[1],sys.argv[2],int(sys.argv[3])\nwith tarfile.open(archive,"r:gz") as source:\n members=source.getmembers()\n if not members or len(members)>100000: raise SystemExit("Ungültige Dateianzahl")\n roots=set(); total=0\n for member in members:\n  item=pathlib.PurePosixPath(member.name)\n  if item.is_absolute() or ".." in item.parts or member.issym() or member.islnk() or member.isdev(): raise SystemExit("Unsicherer Archiveintrag")\n  if item.parts: roots.add(item.parts[0])\n  if member.isfile(): total+=member.size\n  if total>limit: raise SystemExit("Entpackte Daten überschreiten das Sicherheitslimit")\n if len(roots)!=1: raise SystemExit("Ungültiges Stammverzeichnis")\n source.extractall(target,filter="data")\n print(next(iter(roots)))`;
export const dynamic="force-dynamic";export const runtime="nodejs";
export async function POST(request:Request){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const declared=Number(request.headers.get("content-length")||0);if(!request.body)return Response.json({error:"Wähle eine Backup-Datei aus."},{status:400});if(declared>maxBytes)return Response.json({error:`Das Backup ist größer als das erlaubte Uploadlimit von ${Math.round(maxBytes/1024/1024/1024)} GB.`},{status:413});await fs.mkdir(staging,{recursive:true,mode:0o700});const uploadId=crypto.randomUUID(),archive=path.join(staging,`${uploadId}.tar.gz`),extract=path.join(staging,uploadId);let received=0;const source=Readable.fromWeb(request.body as never);source.on("data",chunk=>{received+=chunk.length;if(received>maxBytes)source.destroy(new Error("Backup zu groß"))});try{await pipeline(source,createWriteStream(archive,{mode:0o600}));await fs.mkdir(extract,{mode:0o700});const {stdout}=await exec("python3",["-c",safeExtract,archive,extract,String(maxExpandedBytes)],{timeout:300000,maxBuffer:1024*1024}),rootName=stdout.trim(),content=path.join(extract,rootName),manifest=JSON.parse(await fs.readFile(path.join(content,"manifest.json"),"utf8"));if(manifest.format!=="mein-kraftbaum-backup"||manifest.version!==1)throw new Error("Unbekanntes Backupformat");await exec("sha256sum",["-c","checksums.sha256"],{cwd:content,timeout:300000,maxBuffer:20*1024*1024});const dbFile=path.join(content,"data","kraftbaum.sqlite"),{stdout:integrity}=await exec("sqlite3",[dbFile,"PRAGMA integrity_check;"],{timeout:120000});if(integrity.trim()!=="ok")throw new Error("SQLite-Integritätsprüfung fehlgeschlagen");const dbInfo=await fs.stat(dbFile);audit(admin.id,"backup.upload_validated","backup_upload",uploadId,{createdAt:manifest.createdAt,kind:manifest.kind,revision:manifest.revision,sizeBytes:received});return Response.json({uploadId,valid:true,manifest,databaseBytes:dbInfo.size,totalBytes:received,message:"Backup vollständig geprüft. Für die Wiederherstellung ist eine separate Bestätigung erforderlich."})}catch(error){await fs.rm(archive,{force:true});await fs.rm(extract,{recursive:true,force:true});return Response.json({error:`Backup wurde abgelehnt: ${error instanceof Error?error.message:"Validierung fehlgeschlagen"}`},{status:400})}}
const restoreSchema=z.object({uploadId:z.string().uuid(),confirmation:z.literal("BACKUP WIEDERHERSTELLEN")});
export async function PUT(request:Request){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const parsed=restoreSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Gib zur Bestätigung exakt „BACKUP WIEDERHERSTELLEN“ ein."},{status:400});const archive=path.join(staging,`${parsed.data.uploadId}.tar.gz`);try{await fs.access(archive);await fs.access("/etc/systemd/system/mein-kraftbaum-restore.path")}catch{return Response.json({error:"Der geprüfte Upload oder der sichere Restore-Dienst fehlt. Lade das Backup erneut hoch oder führe einmal das Installationsskript aus."},{status:503})}try{await fs.writeFile(path.join(dataDir,"restore-request.json"),JSON.stringify({uploadId:parsed.data.uploadId,requestedBy:admin.id,requestedAt:new Date().toISOString()}),{flag:"wx",mode:0o600});audit(admin.id,"backup.restore_requested","backup_upload",parsed.data.uploadId);return Response.json({ok:true,message:"Wiederherstellung wurde sicher an den Server übergeben. Die App startet anschließend automatisch neu."},{status:202})}catch(error){if((error as NodeJS.ErrnoException).code==="EEXIST")return Response.json({error:"Eine Wiederherstellung läuft bereits."},{status:409});return Response.json({error:"Restore-Auftrag konnte nicht angelegt werden."},{status:503})}}
