import fs from "node:fs/promises";
import path from "node:path";
import { currentUser } from "@/lib/auth";
import { audit,db,id,now } from "@/lib/database";
import { mediaDir,safeStoredName,validateMedia } from "@/lib/media";

export const runtime="nodejs";export const dynamic="force-dynamic";
type Avatar={id:string;storedName:string;originalName:string;mimeType:string;sizeBytes:number};
function avatar(userId:string){return db.prepare("SELECT m.id,m.stored_name storedName,m.original_name originalName,m.mime_type mimeType,m.size_bytes sizeBytes FROM users u JOIN media_files m ON m.id=u.profile_media_id WHERE u.id=?").get(userId) as Avatar|undefined}
export async function GET(){const user=await currentUser();if(!user)return Response.json({error:"Bitte melde dich an."},{status:401});const row=avatar(user.id);if(!row)return Response.json({error:"Kein Profilbild vorhanden."},{status:404});try{const data=await fs.readFile(path.join(mediaDir,row.storedName));return new Response(data,{headers:{"content-type":row.mimeType,"content-length":String(row.sizeBytes),"content-disposition":`inline; filename*=UTF-8''${encodeURIComponent(row.originalName)}`,"cache-control":"private, no-store","x-content-type-options":"nosniff"}})}catch{return Response.json({error:"Das Profilbild konnte nicht geladen werden."},{status:404})}}
export async function POST(request:Request){const user=await currentUser();if(!user)return Response.json({error:"Bitte melde dich an."},{status:401});const form=await request.formData(),file=form.get("file");if(!(file instanceof File))return Response.json({error:"Bitte wähle ein Bild aus."},{status:400});if(!["image/jpeg","image/png","image/webp"].includes(file.type))return Response.json({error:"Erlaubt sind JPEG-, PNG- und WebP-Bilder."},{status:400});const error=validateMedia(file);if(error)return Response.json({error},{status:400});const previous=avatar(user.id),storedName=safeStoredName(file),mediaId=id(),timestamp=now();try{await fs.writeFile(path.join(mediaDir,storedName),Buffer.from(await file.arrayBuffer()),{mode:0o600,flag:"wx"});db.transaction(()=>{db.prepare("INSERT INTO media_files (id,owner_id,original_name,stored_name,mime_type,size_bytes,created_at) VALUES (?,?,?,?,?,?,?)").run(mediaId,user.id,file.name,storedName,file.type,file.size,timestamp);db.prepare("UPDATE users SET profile_media_id=?,updated_at=? WHERE id=?").run(mediaId,timestamp,user.id);if(previous)db.prepare("DELETE FROM media_files WHERE id=?").run(previous.id)})();if(previous)await fs.unlink(path.join(mediaDir,previous.storedName)).catch(()=>undefined);audit(user.id,previous?"profile.avatar_replace":"profile.avatar_create","user",user.id,{type:file.type,size:file.size});return Response.json({ok:true,profileImage:true},{status:previous?200:201})}catch{await fs.unlink(path.join(mediaDir,storedName)).catch(()=>undefined);return Response.json({error:"Das Profilbild konnte nicht gespeichert werden. Bitte versuche es erneut."},{status:500})}}
export async function DELETE(){const user=await currentUser();if(!user)return Response.json({error:"Bitte melde dich an."},{status:401});const previous=avatar(user.id);if(!previous)return Response.json({error:"Es ist kein Profilbild vorhanden."},{status:404});db.transaction(()=>{db.prepare("UPDATE users SET profile_media_id=NULL,updated_at=? WHERE id=?").run(now(),user.id);db.prepare("DELETE FROM media_files WHERE id=?").run(previous.id)})();await fs.unlink(path.join(mediaDir,previous.storedName)).catch(()=>undefined);audit(user.id,"profile.avatar_delete","user",user.id);return Response.json({ok:true,profileImage:false})}
