import crypto from "node:crypto";
import {currentUser} from "@/lib/auth";
import {audit,db,id,now} from "@/lib/database";
import {refreshCompletion} from "@/lib/progress";
import {sendPush} from "@/lib/push";
const hash=(value:string)=>crypto.createHash("sha256").update(value).digest("hex");
type Checkin={id:string;sessionId:string;title:string;courseId:string;courseTitle:string;expiresAt:string;closedAt:string|null};
function find(token:string){return db.prepare(`SELECT ci.id,ci.session_id sessionId,s.title,s.course_id courseId,c.title courseTitle,ci.expires_at expiresAt,ci.closed_at closedAt FROM session_checkins ci JOIN course_sessions s ON s.id=ci.session_id JOIN courses c ON c.id=s.course_id WHERE ci.token_hash=?`).get(hash(token)) as Checkin|undefined}
export async function GET(_:Request,{params}:{params:Promise<{token:string}>}){const user=await currentUser();if(!user)return Response.json({error:"Bitte melde dich zuerst an.",loginRequired:true},{status:401});const {token}=await params,row=find(token);if(!row)return Response.json({error:"Dieser Check-in-Link ist ungültig."},{status:404});if(row.closedAt||row.expiresAt<=now())return Response.json({error:"Der Check-in ist bereits geschlossen oder abgelaufen."},{status:410});if(!db.prepare("SELECT 1 FROM enrollments WHERE user_id=? AND course_id=?").get(user.id,row.courseId))return Response.json({error:"Du bist diesem Kurs nicht zugeordnet."},{status:403});const attended=Boolean(db.prepare("SELECT 1 FROM attendance WHERE user_id=? AND session_id=?").get(user.id,row.sessionId));return Response.json({title:row.title,courseTitle:row.courseTitle,expiresAt:row.expiresAt,attended});}
export async function POST(_:Request,{params}:{params:Promise<{token:string}>}){const user=await currentUser();if(!user)return Response.json({error:"Bitte melde dich zuerst an.",loginRequired:true},{status:401});const {token}=await params,row=find(token);if(!row)return Response.json({error:"Dieser Check-in-Link ist ungültig."},{status:404});if(row.closedAt||row.expiresAt<=now())return Response.json({error:"Der Check-in ist bereits geschlossen oder abgelaufen."},{status:410});if(!db.prepare("SELECT 1 FROM enrollments WHERE user_id=? AND course_id=?").get(user.id,row.courseId))return Response.json({error:"Du bist diesem Kurs nicht zugeordnet."},{status:403});if(db.prepare("SELECT 1 FROM attendance WHERE user_id=? AND session_id=?").get(user.id,row.sessionId))return Response.json({ok:true,message:"Du warst bereits als anwesend eingetragen."});const timestamp=now();db.prepare("INSERT INTO attendance (id,user_id,session_id,recorded_by,source,note,recorded_at) VALUES (?,?,?,?,?,?,?)").run(id(),user.id,row.sessionId,user.id,"scan","Selbst-Check-in über Termin-QR",timestamp);refreshCompletion(user.id,row.courseId);audit(user.id,"attendance.self_checkin","session",row.sessionId,{checkinId:row.id,userId:user.id,source:"event_qr"});await sendPush(user.id,{title:"Willkommen",body:"Deine Anwesenheit wurde eingetragen und dein Kraftbaum wächst weiter.",url:"/"}).catch(()=>undefined);return Response.json({ok:true,message:"Du bist als anwesend eingetragen. Schön, dass du da bist!"});}
