import {z} from "zod";
import {requireAdmin} from "@/lib/auth";
import {audit,db,id,now} from "@/lib/database";
import {sendPushToCourse} from "@/lib/push";

const batchSchema=z.object({startsAt:z.array(z.string().datetime()).min(1).max(100)});
const legacySchema=z.object({sequence:z.number().int().min(1).max(100),title:z.string().min(2).max(160),startsAt:z.string().datetime(),endsAt:z.string().datetime(),location:z.string().max(240).optional(),navigationUrl:z.url().optional().or(z.literal(""))});
type Course={title:string;sessionCount:number;durationMinutes:number;location:string|null;navigationUrl:string|null};
export async function GET(_:Request,{params}:{params:Promise<{courseId:string}>}){const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const {courseId}=await params;return Response.json({sessions:db.prepare("SELECT id,sequence,title,starts_at startsAt,ends_at endsAt,location,navigation_url navigationUrl FROM course_sessions WHERE course_id=? ORDER BY sequence").all(courseId)});}
export async function POST(request:Request,{params}:{params:Promise<{courseId:string}>}){
  const admin=await requireAdmin();if(!admin)return Response.json({error:"Nicht berechtigt."},{status:403});const {courseId}=await params,body=await request.json().catch(()=>null),batch=batchSchema.safeParse(body),legacy=legacySchema.safeParse(body),course=db.prepare("SELECT title,session_count sessionCount,duration_minutes durationMinutes,location,navigation_url navigationUrl FROM courses WHERE id=?").get(courseId) as Course|undefined;if(!course)return Response.json({error:"Kurs nicht gefunden."},{status:404});
  if(batch.success){const existing=(db.prepare("SELECT COUNT(*) count FROM course_sessions WHERE course_id=?").get(courseId) as {count:number}).count,values=[...new Set(batch.data.startsAt)].sort((a,b)=>Date.parse(a)-Date.parse(b));if(values.length!==batch.data.startsAt.length)return Response.json({error:"Ein Termin wurde doppelt eingegeben."},{status:400});if(existing+values.length>course.sessionCount)return Response.json({error:`Der Kurs hat ${course.sessionCount} Einheiten. Es können noch ${Math.max(0,course.sessionCount-existing)} Termine angelegt werden.`},{status:400});const timestamp=now(),insert=db.prepare("INSERT INTO course_sessions (id,course_id,sequence,title,starts_at,ends_at,location,navigation_url,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)"),created:string[]=[];try{db.transaction(()=>values.forEach((startsAt,index)=>{const sequence=existing+index+1,sessionId=id(),endsAt=new Date(Date.parse(startsAt)+course.durationMinutes*60000).toISOString();insert.run(sessionId,courseId,sequence,`${course.title} · Einheit ${sequence}`,startsAt,endsAt,course.location,course.navigationUrl,timestamp,timestamp);created.push(sessionId)}))()}catch{return Response.json({error:"Mindestens einer dieser Termine ist bereits vorhanden. Bitte prüfe Datum und Uhrzeit."},{status:409})}audit(admin.id,"sessions.create_batch","course",courseId,{count:created.length,firstSequence:existing+1});await sendPushToCourse(courseId,{title:"Neue Kurstermine",body:`${created.length} Kurstermin${created.length===1?" wurde":"e wurden"} eingetragen.`,url:"/"}).catch(()=>undefined);return Response.json({ids:created,count:created.length},{status:201})}
  if(!legacy.success)return Response.json({error:"Bitte gib für jeden Termin Datum und Startzeit an."},{status:400});if(Date.parse(legacy.data.endsAt)<=Date.parse(legacy.data.startsAt))return Response.json({error:"Das Ende muss nach dem Beginn liegen."},{status:400});const sessionId=id(),timestamp=now();try{db.prepare("INSERT INTO course_sessions (id,course_id,sequence,title,starts_at,ends_at,location,navigation_url,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").run(sessionId,courseId,legacy.data.sequence,legacy.data.title,legacy.data.startsAt,legacy.data.endsAt,legacy.data.location||null,legacy.data.navigationUrl||null,timestamp,timestamp)}catch{return Response.json({error:"Für diese Kursnummer besteht bereits ein Termin."},{status:409})}audit(admin.id,"session.create","session",sessionId,{courseId,sequence:legacy.data.sequence});return Response.json({id:sessionId},{status:201});
}
