import { z } from "zod";
import { currentUser } from "@/lib/auth";
import { db,id,now } from "@/lib/database";
import { pushSettings } from "@/lib/push";
const schema=z.object({endpoint:z.url(),keys:z.object({p256dh:z.string().min(10),auth:z.string().min(5)})});
const deleteSchema=z.object({endpoint:z.url()});
export async function GET(request:Request){const user=await currentUser();if(!user)return Response.json({error:"Bitte melde dich an."},{status:401});const settings=pushSettings(),endpoint=new URL(request.url).searchParams.get("endpoint"),count=(db.prepare("SELECT COUNT(*) count FROM push_subscriptions WHERE user_id=? AND enabled=1").get(user.id) as {count:number}).count,enabled=endpoint?Boolean(db.prepare("SELECT 1 FROM push_subscriptions WHERE user_id=? AND endpoint=? AND enabled=1").get(user.id,endpoint)):false;return Response.json({available:Boolean(settings),publicKey:settings?.publicKey||null,enabled,subscriptionCount:count})}
export async function POST(request:Request){const user=await currentUser();if(!user)return Response.json({error:"Bitte melde dich an."},{status:401});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Push-Abonnement ist ungültig."},{status:400});const timestamp=now(),x=parsed.data;db.prepare("INSERT INTO push_subscriptions (id,user_id,endpoint,p256dh,auth,enabled,created_at,updated_at) VALUES (?,?,?,?,?,1,?,?) ON CONFLICT(endpoint) DO UPDATE SET user_id=excluded.user_id,p256dh=excluded.p256dh,auth=excluded.auth,enabled=1,updated_at=excluded.updated_at").run(id(),user.id,x.endpoint,x.keys.p256dh,x.keys.auth,timestamp,timestamp);return Response.json({ok:true})}
export async function DELETE(request:Request){const user=await currentUser();if(!user)return Response.json({error:"Bitte melde dich an."},{status:401});const parsed=deleteSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Die Push-Registrierung dieses Geräts fehlt oder ist ungültig."},{status:400});db.prepare("DELETE FROM push_subscriptions WHERE user_id=? AND endpoint=?").run(user.id,parsed.data.endpoint);return Response.json({ok:true})}
